-- activities registry for the readings repo.
-- EDIT THIS FILE, not Supabase. Re-running patch_readings.py keeps
-- every title and skill tag you change here, and appends new pages.
insert into activities (slug, title, unit, url, max_score, skills, sort_order) values
  ('sept11_reading_guide', 'September 11, 2001 — Reading Guide', 'Other', 'https://tobiasrugger.github.io/readings/sept11_reading_guide.html', null, '{"reading-comprehension"}', 10),
  ('seedfolks-easy', 'Seedfolks: Kim (Easier)', 'Seedfolks', 'https://tobiasrugger.github.io/readings/seedfolks-easy/', null, '{"reading-comprehension"}', 20),
  ('songs/stromae-gender', 'Stromae: What the Video Says About Gender', 'Songs', 'https://tobiasrugger.github.io/readings/songs/stromae-gender/', null, '{"listening"}', 30),
  ('songs/phenomenal-woman', 'Phenomenal Woman — Maya Angelou', 'Songs', 'https://tobiasrugger.github.io/readings/songs/phenomenal-woman/', null, '{"listening"}', 40),
  ('songs/ave-cesaria', 'Ave Cesaria — a prayer for a singer', 'Songs', 'https://tobiasrugger.github.io/readings/songs/ave-cesaria/', null, '{"listening"}', 50),
  ('songs/zombie', 'Song Analysis — "Zombie" by The Cranberries', 'Songs', 'https://tobiasrugger.github.io/readings/songs/zombie/', null, '{"listening"}', 60),
  ('vocab/drinks', 'Drinks', 'Vocabulary', 'https://tobiasrugger.github.io/readings/vocab/drinks/', null, '{"vocabulary"}', 70),
  ('vocab/school-subjects', 'School subjects', 'Vocabulary', 'https://tobiasrugger.github.io/readings/vocab/school-subjects/', null, '{"vocabulary"}', 80),
  ('vocab/foods', 'Foods', 'Vocabulary', 'https://tobiasrugger.github.io/readings/vocab/foods/', null, '{"vocabulary"}', 90),
  ('vocab/animals', 'Animals', 'Vocabulary', 'https://tobiasrugger.github.io/readings/vocab/animals/', null, '{"vocabulary"}', 100),
  ('vocab/sports', 'Sports', 'Vocabulary', 'https://tobiasrugger.github.io/readings/vocab/sports/', null, '{"vocabulary"}', 110),
  ('vocab/colors', 'Colors', 'Vocabulary', 'https://tobiasrugger.github.io/readings/vocab/colors/', null, '{"vocabulary"}', 120),
  ('mlk', 'Rev. Dr. Martin Luther King, Jr. — Reading Guide', 'MLK', 'https://tobiasrugger.github.io/readings/mlk/', null, '{"reading-comprehension"}', 130),
  ('mlk/mlk', 'Rev. Dr. Martin Luther King, Jr. — Reading Guide', 'MLK', 'https://tobiasrugger.github.io/readings/mlk/mlk.html', null, '{"reading-comprehension"}', 140),
  ('human-rights', 'Human Rights & the UDHR', 'Human Rights', 'https://tobiasrugger.github.io/readings/human-rights/', null, '{"reading-comprehension"}', 150),
  ('resume', 'My Résumé', 'Resume', 'https://tobiasrugger.github.io/readings/resume/', null, '{"life-skills"}', 160),
  ('resume/lesson1', 'Résumé Lesson 1 — What Counts?', 'Resume', 'https://tobiasrugger.github.io/readings/resume/lesson1.html', null, '{"life-skills"}', 170),
  ('resume/lesson2', 'Résumé Lesson 2 — Sections & One-Liners', 'Resume', 'https://tobiasrugger.github.io/readings/resume/lesson2.html', null, '{"life-skills"}', 180),
  ('resume/lesson3', 'Résumé Lesson 3 — Polish & Send', 'Resume', 'https://tobiasrugger.github.io/readings/resume/lesson3.html', null, '{"life-skills"}', 190),
  ('tyma-vocab', 'Thank You, Ma''am — Words Before We Read', 'Thank You Ma''am', 'https://tobiasrugger.github.io/readings/tyma-vocab/', null, '{"vocabulary","reading-comprehension"}', 200),
  ('stand-by-me/anticipation', 'Agree / Disagree — The Body & Stand By Me', 'Stand By Me', 'https://tobiasrugger.github.io/readings/stand-by-me/anticipation.html', null, '{"predicting"}', 210),
  ('stand-by-me/characters', 'Stand By Me — Character Study', 'Stand By Me', 'https://tobiasrugger.github.io/readings/stand-by-me/characters.html', null, '{"literary-analysis"}', 220),
  ('stand-by-me/guide-easy', 'Reading Guide #1 — The Body / Stand By Me', 'Stand By Me', 'https://tobiasrugger.github.io/readings/stand-by-me/guide-easy.html', null, '{"reading-comprehension"}', 230),
  ('stand-by-me/painting', 'Reading the Painting — Stand By Me', 'Stand By Me', 'https://tobiasrugger.github.io/readings/stand-by-me/painting.html', null, '{"reading-comprehension"}', 240),
  ('stand-by-me/part1', 'Reading Guide — The Body, Part 1 (original text)', 'Stand By Me', 'https://tobiasrugger.github.io/readings/stand-by-me/part1.html', null, '{"reading-comprehension"}', 250),
  ('stand-by-me/part1a', 'The Body Part 1a — Reading Guide', 'Stand By Me', 'https://tobiasrugger.github.io/readings/stand-by-me/part1a.html', null, '{"reading-comprehension"}', 260),
  ('stand-by-me/vocab', 'Vocabulary Practice #1 — The Body / Stand By Me', 'Stand By Me', 'https://tobiasrugger.github.io/readings/stand-by-me/vocab.html', null, '{"vocabulary"}', 270),
  ('manzanar/assessment', 'Unit Assessment — Farewell to Manzanar', 'Farewell to Manzanar', 'https://tobiasrugger.github.io/readings/manzanar/assessment.html', null, '{"assessment"}', 280),
  ('manzanar/ch1', 'Ch. 1 — Farewell to Manzanar', 'Farewell to Manzanar', 'https://tobiasrugger.github.io/readings/manzanar/ch1.html', null, '{"reading-comprehension"}', 290),
  ('manzanar/ch2', 'Ch. 2 — Farewell to Manzanar', 'Farewell to Manzanar', 'https://tobiasrugger.github.io/readings/manzanar/ch2.html', null, '{"reading-comprehension"}', 300),
  ('manzanar/grammar', 'Grammar Practice — Manzanar', 'Farewell to Manzanar', 'https://tobiasrugger.github.io/readings/manzanar/grammar.html', null, '{"grammar"}', 310),
  ('manzanar', 'Farewell to Manzanar — ELD Unit', 'Farewell to Manzanar', 'https://tobiasrugger.github.io/readings/manzanar/', null, '{"reading-comprehension"}', 320),
  ('manzanar/movie', 'Movie Guide — Farewell to Manzanar (1976)', 'Farewell to Manzanar', 'https://tobiasrugger.github.io/readings/manzanar/movie.html', null, '{"reading-comprehension"}', 330),
  ('stromae-gender', 'Stromae: What the Video Says About Gender', 'Songs', 'https://tobiasrugger.github.io/readings/stromae-gender/', null, '{"reading-comprehension"}', 340),
  ('phenomenal-woman', 'Phenomenal Woman — Maya Angelou', 'Poems', 'https://tobiasrugger.github.io/readings/phenomenal-woman/', null, '{"reading-comprehension"}', 350),
  ('toolkits/lesson1', 'Describing yourself', 'Toolkits', 'https://tobiasrugger.github.io/readings/toolkits/lesson1.html', null, '{"describing"}', 360),
  ('toolkits/lesson2', 'Describing a classmate', 'Toolkits', 'https://tobiasrugger.github.io/readings/toolkits/lesson2.html', null, '{"describing"}', 370),
  ('toolkits/lesson3', 'Describing a character', 'Toolkits', 'https://tobiasrugger.github.io/readings/toolkits/lesson3.html', null, '{"literary-analysis","describing"}', 380),
  ('toolkits/lesson3b', 'Lesson #3b — Venn diagram and comparing sentences', 'Toolkits', 'https://tobiasrugger.github.io/readings/toolkits/lesson3b.html', null, '{"reading-comprehension"}', 390),
  ('toolkits/lesson4', 'Lesson #4 — Compare and contrast practice 1', 'Toolkits', 'https://tobiasrugger.github.io/readings/toolkits/lesson4.html', null, '{"reading-comprehension"}', 400),
  ('toolkits/lesson5', 'Lesson #5 — Compare and contrast practice 2', 'Toolkits', 'https://tobiasrugger.github.io/readings/toolkits/lesson5.html', null, '{"reading-comprehension"}', 410),
  ('toolkits/toolkit1-practice', 'Toolkit #1 practice — Pronouns', 'Toolkits', 'https://tobiasrugger.github.io/readings/toolkits/toolkit1-practice.html', null, '{"speaking-listening"}', 420),
  ('toolkits/toolkit1', 'Toolkit #1 — Pronouns', 'Toolkits', 'https://tobiasrugger.github.io/readings/toolkits/toolkit1.html', null, '{"speaking-listening"}', 430),
  ('toolkits/toolkit2-practice', 'Toolkit #2 practice — to be, to have, to do', 'Toolkits', 'https://tobiasrugger.github.io/readings/toolkits/toolkit2-practice.html', null, '{"reading-comprehension"}', 440),
  ('toolkits/toolkit2', 'Toolkit #2 — to be, to have, to do', 'Toolkits', 'https://tobiasrugger.github.io/readings/toolkits/toolkit2.html', null, '{"reading-comprehension"}', 450),
  ('toolkits/toolkit3-practice', 'Toolkit #3 practice — Compare and contrast', 'Toolkits', 'https://tobiasrugger.github.io/readings/toolkits/toolkit3-practice.html', null, '{"reading-comprehension"}', 460),
  ('toolkits/toolkit3', 'Toolkit #3 — Compare and contrast', 'Toolkits', 'https://tobiasrugger.github.io/readings/toolkits/toolkit3.html', null, '{"reading-comprehension"}', 470),
  ('romeo-juliet/assess', 'Romeo and Juliet — Assessment Center', 'Romeo and Juliet', 'https://tobiasrugger.github.io/readings/romeo-juliet/assess.html', null, '{"assessment"}', 480),
  ('romeo-juliet/grammar', 'Romeo and Juliet — Grammar & Language Lab', 'Romeo and Juliet', 'https://tobiasrugger.github.io/readings/romeo-juliet/grammar.html', null, '{"grammar"}', 490),
  ('romeo-juliet', 'Romeo and Juliet — ELD Unit', 'Romeo and Juliet', 'https://tobiasrugger.github.io/readings/romeo-juliet/', null, '{"reading-comprehension"}', 500),
  ('romeo-juliet/scenes', 'Romeo and Juliet — Scene Reading Guides', 'Romeo and Juliet', 'https://tobiasrugger.github.io/readings/romeo-juliet/scenes.html', null, '{"reading-comprehension"}', 510),
  ('seedfolks', 'Seedfolks Chapter 1: Kim', 'Seedfolks', 'https://tobiasrugger.github.io/readings/seedfolks/', null, '{"reading-comprehension"}', 520),
  ('fables', 'Short Stories & Fables', 'Fables', 'https://tobiasrugger.github.io/readings/fables/', null, '{"reading-comprehension"}', 530),
  ('gratitude', 'Gratitude', 'Gratitude', 'https://tobiasrugger.github.io/readings/gratitude/', null, '{"reading-comprehension"}', 540),
  ('eld103-unit1', 'ELD 103 — Unit 1: Introducing People', 'ELD 103 Writing', 'https://tobiasrugger.github.io/readings/eld103-unit1/', null, '{"reading-comprehension"}', 550),
  ('favorite-songs/class-mixtape', 'The class mixtape', 'Favorite Songs', 'https://tobiasrugger.github.io/readings/favorite-songs/class-mixtape.html', null, '{"listening","describing"}', 560),
  ('favorite-songs/feelings', 'Music Words 2: How does it make you feel?', 'Favorite Songs', 'https://tobiasrugger.github.io/readings/favorite-songs/feelings.html', null, '{"vocabulary","listening","describing"}', 570),
  ('favorite-songs', 'Our Favorite Songs', 'Favorite Songs', 'https://tobiasrugger.github.io/readings/favorite-songs/', null, '{"listening","describing"}', 580),
  ('favorite-songs/my-song', 'Add my song', 'Favorite Songs', 'https://tobiasrugger.github.io/readings/favorite-songs/my-song.html', null, '{"listening","describing"}', 590),
  ('favorite-songs/sound', 'Music Words 1: How does it sound?', 'Favorite Songs', 'https://tobiasrugger.github.io/readings/favorite-songs/sound.html', null, '{"vocabulary","speaking-listening","listening","describing"}', 600),
  ('psychology/assessment', 'Unit Assessment — Who Am I?', 'Psychology', 'https://tobiasrugger.github.io/readings/psychology/assessment.html', null, '{"assessment"}', 610),
  ('psychology/grammar', 'Grammar Gym — Who Am I?', 'Psychology', 'https://tobiasrugger.github.io/readings/psychology/grammar.html', null, '{"grammar"}', 620),
  ('psychology', 'Who Am I? — Psychology & Short Stories', 'Psychology', 'https://tobiasrugger.github.io/readings/psychology/', null, '{"reading-comprehension"}', 630),
  ('psychology/p1-psychology', 'What Is Psychology?', 'Psychology', 'https://tobiasrugger.github.io/readings/psychology/p1-psychology.html', null, '{"reading-comprehension"}', 640),
  ('psychology/p2-five-factors', 'The Big Five', 'Psychology', 'https://tobiasrugger.github.io/readings/psychology/p2-five-factors.html', null, '{"reading-comprehension"}', 650),
  ('psychology/p3-somebody', 'The Somebody', 'Psychology', 'https://tobiasrugger.github.io/readings/psychology/p3-somebody.html', null, '{"reading-comprehension"}', 660),
  ('psychology/p4-selves', 'Actual, Ideal, Ought', 'Psychology', 'https://tobiasrugger.github.io/readings/psychology/p4-selves.html', null, '{"reading-comprehension"}', 670),
  ('psychology/p5-jacket', 'The Jacket', 'Psychology', 'https://tobiasrugger.github.io/readings/psychology/p5-jacket.html', null, '{"reading-comprehension"}', 680),
  ('psychology/p6-influence', 'Influence', 'Psychology', 'https://tobiasrugger.github.io/readings/psychology/p6-influence.html', null, '{"reading-comprehension"}', 690),
  ('psychology/writing', 'Writing Workshop — PEA Paragraphs', 'Psychology', 'https://tobiasrugger.github.io/readings/psychology/writing.html', null, '{"writing","life-skills"}', 700),
  ('survival-english/assessment', 'Survival English — Unit 1 Test', 'Survival English', 'https://tobiasrugger.github.io/readings/survival-english/assessment.html', null, '{"assessment","life-skills"}', 710),
  ('survival-english', 'Survival English — Unit 1', 'Survival English', 'https://tobiasrugger.github.io/readings/survival-english/', null, '{"life-skills"}', 720),
  ('grasshopper-ant/assessment', 'Unit Assessment — The Grasshopper and the Ant', 'Fables', 'https://tobiasrugger.github.io/readings/grasshopper-ant/assessment.html', null, '{"assessment"}', 730),
  ('grasshopper-ant/grammar', 'Grammar — The Grasshopper and the Ant', 'Fables', 'https://tobiasrugger.github.io/readings/grasshopper-ant/grammar.html', null, '{"grammar"}', 740),
  ('grasshopper-ant/reading', 'The Grasshopper and the Ant — Reading Guide', 'Fables', 'https://tobiasrugger.github.io/readings/grasshopper-ant/reading.html', null, '{"reading-comprehension"}', 750),
  ('grasshopper-ant/writing', 'Are You an Ant or a Grasshopper? — Read & Write', 'Fables', 'https://tobiasrugger.github.io/readings/grasshopper-ant/writing.html', null, '{"reading-comprehension","writing"}', 760),
  ('arrival', 'The Arrival — Unit Guide', 'Arrival Stories', 'https://tobiasrugger.github.io/readings/arrival/', null, '{"reading-comprehension"}', 770),
  ('arrival/projects', 'The Arrival — Final Projects', 'Arrival Stories', 'https://tobiasrugger.github.io/readings/arrival/projects.html', null, '{"reading-comprehension"}', 780),
  ('odyssey', 'The Odyssey — ELD Unit', 'The Odyssey', 'https://tobiasrugger.github.io/readings/odyssey/', null, '{"reading-comprehension"}', 790),
  ('news', 'This Week''s Reading', 'Every Week', 'https://tobiasrugger.github.io/readings/news/', null, '{"reading-comprehension"}', 800),
  ('this-is-how', 'This Is How We Do It & This Is How I Do It — Unit', 'This Is How', 'https://tobiasrugger.github.io/readings/this-is-how/', null, '{"reading-comprehension"}', 810),
  ('thoughts', 'Be Careful of Your Thoughts — Reading & Activities', 'Grammar', 'https://tobiasrugger.github.io/readings/thoughts/', null, '{"reading-comprehension"}', 820),
  ('oral-histories', 'Oral Histories & the Family Interview', 'Oral Histories', 'https://tobiasrugger.github.io/readings/oral-histories/', null, '{"speaking-listening"}', 830),
  ('holidays', 'Ghosts, Candy, and Remembering', 'Holidays', 'https://tobiasrugger.github.io/readings/holidays/', null, '{"reading-comprehension"}', 840),
  ('ave-cesaria', 'Ave Cesaria — a prayer for a singer', 'Songs', 'https://tobiasrugger.github.io/readings/ave-cesaria/', null, '{"reading-comprehension"}', 850),
  ('gratitude-letters', 'Letter to My Fifth Grade Teacher', 'Gratitude', 'https://tobiasrugger.github.io/readings/gratitude-letters/', null, '{"reading-comprehension"}', 860),
  ('favorites', 'My Favorite Things', 'Favorites', 'https://tobiasrugger.github.io/readings/favorites/', null, '{"describing"}', 870),
  ('maus/anthology', 'Class Anthology — Oral Histories', 'Maus', 'https://tobiasrugger.github.io/readings/maus/anthology.html', null, '{"speaking-listening"}', 880),
  ('maus/assessment', 'Maus — Final Assessment — Maus Unit', 'Maus', 'https://tobiasrugger.github.io/readings/maus/assessment.html', null, '{"assessment"}', 890),
  ('maus/background', 'Before Maus — Background & How to Read a Comic — Maus Unit', 'Maus', 'https://tobiasrugger.github.io/readings/maus/background.html', null, '{"reading-comprehension"}', 900),
  ('maus', 'Maus, the Holocaust & Oral Histories — Maus Unit', 'Maus', 'https://tobiasrugger.github.io/readings/maus/', null, '{"speaking-listening"}', 910),
  ('maus/oralhistory', 'Oral History — Final Project — Maus Unit', 'Maus', 'https://tobiasrugger.github.io/readings/maus/oralhistory.html', null, '{"speaking-listening"}', 920),
  ('maus/reading', 'Maus — Reading Guides — Maus Unit', 'Maus', 'https://tobiasrugger.github.io/readings/maus/reading.html', null, '{"reading-comprehension"}', 930),
  ('maus/vocab', 'Vocabulary Gym — Maus Unit', 'Maus', 'https://tobiasrugger.github.io/readings/maus/vocab.html', null, '{"vocabulary"}', 940),
  ('sept11', 'September 11, 2001 — Reading Guide', 'September 11', 'https://tobiasrugger.github.io/readings/sept11/', null, '{"reading-comprehension"}', 950),
  ('sept11-easy', 'September 11, 2001 — Easy Reading Guide', 'September 11', 'https://tobiasrugger.github.io/readings/sept11-easy/', null, '{"reading-comprehension"}', 960),
  ('eld103', 'ELD 103 — Academic Writing: Paragraphs & Narratives', 'ELD 103 Writing', 'https://tobiasrugger.github.io/readings/eld103/', null, '{"writing"}', 970)
on conflict (slug) do update
  set title      = excluded.title,
      unit       = excluded.unit,
      url        = excluded.url,
      skills     = excluded.skills,
      sort_order = excluded.sort_order;
