/* data.js — Is There a Face on Mars? (VETS Story 05). One source of truth for every practice page. */
window.SD = window.SD || {};
SD.STORY = 'story-05';
SD.NN = '05';
SD.TITLE = "Is There a Face on Mars?";
SD.SUB = "A spaceship takes photos of Mars. People see something strange.";
SD.STORY_URL = '../vets_story_05.html';
SD.ART = {};
SD.VOCAB = [{"w": "spaceship", "pic": "🚀", "gloss": "a vehicle that goes to space", "s": "A ___ goes up."}, {"w": "Mars", "pic": "🪐", "gloss": "a red planet", "s": "It goes to ___."}, {"w": "camera", "pic": "📷", "gloss": "it takes photos", "s": "There is a ___ in the spaceship."}, {"w": "photo", "pic": "🖼️", "gloss": "a picture from a camera", "s": "In one ___, there is a face."}, {"w": "face", "pic": "🙂", "gloss": "eyes, nose and mouth", "s": "There is a ___ on Mars!"}, {"w": "eyes", "pic": "👀", "gloss": "you see with them", "s": "The face has ___."}, {"w": "nose", "pic": "👃", "gloss": "you smell with it", "s": "The face has a ___."}, {"w": "mouth", "pic": "👄", "gloss": "you eat and talk with it", "s": "The face has a ___."}, {"w": "newspapers", "pic": "📰", "gloss": "you read the news in them", "s": "The photo is in many ___."}, {"w": "scientists", "pic": "🧑‍🔬", "gloss": "people who study science", "s": "“No,” the ___ say."}, {"w": "hill", "pic": "⛰️", "gloss": "a small mountain", "s": "It’s a ___."}, {"w": "shadow", "pic": "🌑", "gloss": "a dark shape made by light", "s": "Light and ___ make the face."}];
SD.SENTS = ["It is 1976.", "A spaceship goes up.", "It goes to Mars.", "There is a camera in the spaceship.", "The camera takes photos of Mars.", "In one photo, there is a face on Mars!", "The face has eyes, a nose, and a mouth.", "The face is very big.", "It is one mile wide!", "The photo is in many newspapers.", "People say, “Look! There’s a face on Mars!”", "“No,” the scientists say.", "“It’s not a face. It’s a hill.”", "Light and shadow make the face."];
SD.SOUNDS = [{"name": "a as in camera", "key": "camera", "words": ["at", "has", "and", "shadow", "camera"]}, {"name": "a as in face", "key": "face", "words": ["take", "face", "say", "make", "space"]}, {"name": "o as in photo", "key": "photo", "words": ["go", "photo", "no", "nose", "so"]}, {"name": "u as in up", "key": "up", "words": ["up", "of", "a", "what", "one"]}];
SD.SPELL = [{"w": "take", "hide": [1]}, {"w": "face", "hide": [2]}, {"w": "newspaper", "hide": [2, 4, 7]}, {"w": "people", "hide": [2, 4]}, {"w": "wide", "hide": [1]}, {"w": "hill", "hide": [2, 3]}, {"w": "light", "hide": [1, 3]}, {"w": "photo", "hide": [1, 3]}, {"w": "camera", "hide": [1, 3]}, {"w": "shadow", "hide": [2, 4]}];
SD.WRITE = ["A spaceship goes to Mars.", "The camera takes photos.", "There is a face on Mars!", "The face has eyes, a nose, and a mouth.", "The photo is in many newspapers.", "It is not a face.", "Light and shadow make the face."];
SD.DICT = {"word": [{"say": "face", "opts": ["face", "fast", "vase"]}, {"say": "Mars", "opts": ["Mars", "cars", "March"]}, {"say": "nose", "opts": ["nose", "knows", "rose"]}, {"say": "hill", "opts": ["hill", "hell", "heel"]}, {"say": "light", "opts": ["light", "right", "late"]}, {"say": "photo", "opts": ["photo", "potato", "motto"]}, {"say": "mile", "opts": ["mile", "mild", "meal"]}, {"say": "eyes", "opts": ["eyes", "ice", "ease"]}], "phrase": [{"say": "a face on Mars", "extra": ["Earth"]}, {"say": "eyes, a nose, and a mouth", "extra": ["ears"]}, {"say": "one mile wide", "extra": ["high"]}, {"say": "in many newspapers", "extra": ["books"]}, {"say": "light and shadow", "extra": ["dark"]}, {"say": "it’s a hill", "extra": ["face"]}], "sentence": [{"say": "A spaceship goes to Mars.", "extra": ["moon"]}, {"say": "The camera takes photos.", "extra": ["makes"]}, {"say": "There is a face on Mars.", "extra": ["are"]}, {"say": "The face is very big.", "extra": ["small"]}, {"say": "It is not a face.", "extra": ["hill"]}, {"say": "Light and shadow make the face.", "extra": ["take"]}]};
SD.GRAMMAR = [{"id": "there", "title": "There is / there are", "skill": "THERE.BE", "items": [{"p": "___ a face on Mars!", "o": ["There is", "There are", "It is"], "a": "There is"}, {"p": "___ eyes and a nose.", "o": ["There are", "There is", "They is"], "a": "There are"}, {"p": "___ a camera in the spaceship.", "o": ["There is", "There are", "Here are"], "a": "There is"}, {"p": "___ many newspapers.", "o": ["There are", "There is", "There’s"], "a": "There are"}]}, {"id": "neg", "title": "It’s not", "skill": "NEG.BE", "items": [{"p": "It’s ___ a face.", "o": ["not", "no", "don’t"], "a": "not"}, {"p": "The face ___ real.", "o": ["isn’t", "aren’t", "don’t"], "a": "isn’t"}, {"p": "They ___ right.", "o": ["aren’t", "isn’t", "not"], "a": "aren’t"}]}, {"id": "has", "title": "Has / have", "skill": "HAVE.PRES", "items": [{"p": "The face ___ eyes.", "o": ["has", "have", "is"], "a": "has"}, {"p": "People ___ cameras.", "o": ["have", "has", "haves"], "a": "have"}, {"p": "The spaceship ___ a camera.", "o": ["has", "have", "had"], "a": "has"}]}, {"id": "a", "title": "A face, an eye", "skill": "ART.AN", "items": [{"p": "It is ___ hill.", "o": ["a", "an", "the a"], "a": "a"}, {"p": "The face has ___ nose.", "o": ["a", "an", "one of"], "a": "a"}, {"p": "I see ___ eye.", "o": ["an", "a", "the an"], "a": "an"}]}];
SD.ME = {"prompt": "Is it a face or a hill? What do you think? Finish the sentence, then say it.", "before": "I think it is a", "after": "on Mars.", "options": ["face", "hill", "face and a hill"]};
