/* data.js — A Son for Mr. & Mrs. Aversa? (VETS Story 04). One source of truth for every practice page. */
window.SD = window.SD || {};
SD.STORY = 'story-04';
SD.NN = '04';
SD.TITLE = "A Son for Mr. & Mrs. Aversa?";
SD.SUB = "A couple expects one baby. The doctor has news.";
SD.STORY_URL = '../vets_story_04.html';
SD.ART = {};
SD.VOCAB = [{"w": "daughters", "pic": "👧", "gloss": "girl children", "s": "They have two ___."}, {"w": "son", "pic": "👦", "gloss": "a boy child", "s": "They want a ___."}, {"w": "love", "pic": "❤️", "gloss": "like very, very much", "s": "They ___ their daughters."}, {"w": "doctor", "pic": "👩‍⚕️", "gloss": "a person who helps sick people", "s": "Mrs. Aversa goes to the ___."}, {"w": "babies", "pic": "👶", "gloss": "very young children", "s": "There are four ___!"}, {"w": "born", "pic": "🏥", "gloss": "comes into the world", "s": "The first baby is ___."}, {"w": "girl", "pic": "👩", "gloss": "a female child", "s": "“It’s a ___!”"}, {"w": "boy", "pic": "👨", "gloss": "a male child", "s": "Maybe one baby is a ___."}, {"w": "first", "pic": "1️⃣", "gloss": "number one", "s": "The ___ baby is born."}, {"w": "second", "pic": "2️⃣", "gloss": "number two", "s": "The ___ baby is a girl."}, {"w": "another", "pic": "➕", "gloss": "one more", "s": "The fourth baby is ___ girl!"}, {"w": "happy", "pic": "😊", "gloss": "feeling good", "s": "We are ___ with six daughters!"}];
SD.SENTS = ["Mr. and Mrs. Aversa have two daughters.", "They love their daughters very much.", "But they want a son, too.", "Mrs. Aversa goes to the doctor.", "The doctor says, “There are four babies!”", "The first baby is born.", "“It’s a girl!”", "The second baby is a girl.", "The third baby is a girl.", "The fourth baby is another girl!", "All four babies are girls.", "Now Mr. and Mrs. Aversa have six daughters.", "Do they want more babies?", "“No,” they say.", "“We are happy with six daughters!”"];
SD.SOUNDS = [{"name": "u as in love", "key": "love", "words": ["love", "son", "another", "but", "much"]}, {"name": "o as in doctor", "key": "doctor", "words": ["doctor", "hospital", "want", "not", "on"]}, {"name": "oo as in two", "key": "two", "words": ["to", "too", "two", "do", "you"]}, {"name": "or as in four", "key": "four", "words": ["more", "four", "born", "for", "door"]}];
SD.SPELL = [{"w": "love", "hide": [1]}, {"w": "very", "hide": [3]}, {"w": "much", "hide": [2, 3]}, {"w": "doctor", "hide": [2, 4]}, {"w": "babies", "hide": [1, 3]}, {"w": "another", "hide": [1, 5]}, {"w": "daughter", "hide": [2, 3]}, {"w": "son", "hide": [1]}, {"w": "first", "hide": [1, 2]}, {"w": "fourth", "hide": [1, 2]}];
SD.WRITE = ["They have two daughters.", "They want a son too.", "There are four babies!", "The first baby is a girl.", "All four babies are girls.", "Now they have six daughters.", "We are happy with six daughters!"];
SD.DICT = {"word": [{"say": "son", "opts": ["son", "sun", "soon"]}, {"say": "four", "opts": ["four", "for", "door"]}, {"say": "girl", "opts": ["girl", "curl", "girls"]}, {"say": "boy", "opts": ["boy", "buy", "bay"]}, {"say": "born", "opts": ["born", "barn", "burn"]}, {"say": "babies", "opts": ["babies", "baby", "bodies"]}, {"say": "first", "opts": ["first", "fast", "thirst"]}, {"say": "daughter", "opts": ["daughter", "doctor", "water"]}], "phrase": [{"say": "two daughters", "extra": ["sons"]}, {"say": "a son too", "extra": ["daughter"]}, {"say": "four babies", "extra": ["three"]}, {"say": "the first baby", "extra": ["second"]}, {"say": "another girl", "extra": ["boy"]}, {"say": "six daughters", "extra": ["five"]}], "sentence": [{"say": "They want a son too.", "extra": ["daughter"]}, {"say": "There are four babies!", "extra": ["girls"]}, {"say": "The second baby is a girl.", "extra": ["boy"]}, {"say": "All four babies are girls.", "extra": ["boys"]}, {"say": "Now they have six daughters.", "extra": ["sons"]}, {"say": "We are happy with six daughters.", "extra": ["sad"]}]};
SD.GRAMMAR = [{"id": "ord", "title": "First, second, third, fourth", "skill": "NUM.ORD", "items": [{"p": "The ___ baby is born. Then the second.", "o": ["first", "one", "once"], "a": "first"}, {"p": "One, two, three: the ___ baby is a girl.", "o": ["third", "three", "thirty"], "a": "third"}, {"p": "After the third baby, the ___ baby is born.", "o": ["fourth", "four", "forth"], "a": "fourth"}, {"p": "The ___ baby comes after the first.", "o": ["second", "two", "twice"], "a": "second"}]}, {"id": "plural", "title": "One baby, four babies", "skill": "NOUN.PL", "items": [{"p": "They have two ___.", "o": ["daughters", "daughter", "daughteres"], "a": "daughters"}, {"p": "There are four ___!", "o": ["babies", "baby", "babys"], "a": "babies"}, {"p": "They want one ___.", "o": ["son", "sons", "a sons"], "a": "son"}, {"p": "All four babies are ___.", "o": ["girls", "girl", "girles"], "a": "girls"}]}, {"id": "there", "title": "There is / there are", "skill": "THERE.BE", "items": [{"p": "___ four babies.", "o": ["There are", "There is", "They are"], "a": "There are"}, {"p": "___ a doctor in the room.", "o": ["There is", "There are", "It is"], "a": "There is"}, {"p": "___ six daughters now.", "o": ["There are", "There is", "There be"], "a": "There are"}]}, {"id": "want", "title": "Want + noun", "skill": "WANT.N", "items": [{"p": "They ___ a son.", "o": ["want", "wants", "wanting"], "a": "want"}, {"p": "Mrs. Aversa ___ a boy.", "o": ["wants", "want", "is want"], "a": "wants"}, {"p": "Do they want ___ babies?", "o": ["more", "much", "many of"], "a": "more"}]}];
SD.ME = {"prompt": "The Aversas have six daughters. And you? Finish the sentence, then say it.", "before": "I have", "after": "brothers and sisters.", "options": ["no", "one", "two", "three", "four", "five", "six", "many"]};
