/* data.js — Elevator Romance (VETS Story 03). One source of truth for every practice page. */
window.SD = window.SD || {};
SD.STORY = 'story-03';
SD.NN = '03';
SD.TITLE = "Elevator Romance";
SD.SUB = "A man and a woman are stuck for 19 hours.";
SD.STORY_URL = '../vets_story_03.html';
SD.ART = {};
SD.VOCAB = [{"w": "elevator", "pic": "🛗", "gloss": "a small room that goes up and down in a building", "s": "A young man gets on an ___."}, {"w": "young", "pic": "🧑", "gloss": "not old", "s": "A ___ man gets on."}, {"w": "stops", "pic": "✋", "gloss": "does not move", "s": "The elevator ___."}, {"w": "stuck", "pic": "🚫", "gloss": "cannot move", "s": "It is ___ between floors."}, {"w": "floors", "pic": "🏢", "gloss": "levels of a building", "s": "It is stuck between ___."}, {"w": "hours", "pic": "⏰", "gloss": "60 minutes each", "s": "They are together for 19 ___."}, {"w": "talk", "pic": "🗣️", "gloss": "say words to each other", "s": "They ___, and talk, and talk."}, {"w": "doors", "pic": "🚪", "gloss": "you open them to go in or out", "s": "The ___ open."}, {"w": "tired", "pic": "😴", "gloss": "wanting to rest", "s": "They are ___."}, {"w": "hungry", "pic": "🍔", "gloss": "wanting food", "s": "They are ___."}, {"w": "thirsty", "pic": "🥤", "gloss": "wanting a drink", "s": "They are ___."}, {"w": "married", "pic": "💒", "gloss": "husband and wife", "s": "Three months later, they get ___!"}];
SD.SENTS = ["A young man gets on an elevator.", "The elevator goes up.", "The elevator stops.", "A young woman gets on the elevator.", "The elevator goes up.", "Then it stops.", "It doesn’t go up.", "It doesn’t go down.", "It is stuck between floors.", "The elevator is stuck for 19 hours!", "They talk, and talk, and talk.", "Finally, the elevator goes up.", "The doors open.", "They are tired.", "They are hungry.", "They are thirsty.", "And they are in love!", "Three months later, they get married!"];
SD.SOUNDS = [{"name": "o as in stop", "key": "stop", "words": ["stops", "on", "doctor", "not", "hot"]}, {"name": "u as in up", "key": "up", "words": ["up", "hungry", "stuck", "but", "love"]}, {"name": "ur / ir as in thirsty", "key": "thirsty", "words": ["thirsty", "girl", "first", "her", "turn"]}];
SD.SPELL = [{"w": "talk", "hide": [2]}, {"w": "walk", "hide": [1]}, {"w": "tired", "hide": [1, 3]}, {"w": "hungry", "hide": [0, 3]}, {"w": "thirsty", "hide": [1, 4]}, {"w": "months", "hide": [2, 4]}, {"w": "later", "hide": [1, 3]}, {"w": "married", "hide": [1, 4]}, {"w": "doors", "hide": [1, 2]}, {"w": "elevator", "hide": [2, 5]}];
SD.WRITE = ["A young man gets on an elevator.", "The elevator stops.", "It is stuck between floors.", "They talk and talk.", "The doors open.", "They are in love!", "Three months later they get married."];
SD.DICT = {"word": [{"say": "up", "opts": ["up", "cup", "hop"]}, {"say": "stops", "opts": ["stops", "steps", "tops"]}, {"say": "talk", "opts": ["talk", "walk", "took"]}, {"say": "tired", "opts": ["tired", "tied", "tire"]}, {"say": "hungry", "opts": ["hungry", "angry", "hundred"]}, {"say": "thirsty", "opts": ["thirsty", "thirty", "Thursday"]}, {"say": "doors", "opts": ["doors", "does", "dose"]}, {"say": "married", "opts": ["married", "marry", "merry"]}], "phrase": [{"say": "a young man", "extra": ["woman"]}, {"say": "between floors", "extra": ["doors"]}, {"say": "for 19 hours", "extra": ["90"]}, {"say": "talk and talk", "extra": ["walk"]}, {"say": "the doors open", "extra": ["close"]}, {"say": "three months later", "extra": ["weeks"]}], "sentence": [{"say": "The elevator goes up.", "extra": ["down"]}, {"say": "A young woman gets on the elevator.", "extra": ["off"]}, {"say": "It is stuck between floors.", "extra": ["doors"]}, {"say": "They talk and talk and talk.", "extra": ["walk"]}, {"say": "They are tired and hungry.", "extra": ["happy"]}, {"say": "Three months later they get married.", "extra": ["years"]}]};
SD.GRAMMAR = [{"id": "be", "title": "They are, it is", "skill": "BE.PRES", "items": [{"p": "They ___ tired.", "o": ["are", "is", "am"], "a": "are"}, {"p": "The elevator ___ stuck.", "o": ["is", "are", "am"], "a": "is"}, {"p": "A young man ___ in the elevator.", "o": ["is", "are", "be"], "a": "is"}, {"p": "The man and the woman ___ in love.", "o": ["are", "is", "be"], "a": "are"}]}, {"id": "neg", "title": "Doesn’t", "skill": "NEG.DOES", "items": [{"p": "It ___ go up.", "o": ["doesn’t", "don’t", "isn’t"], "a": "doesn’t"}, {"p": "The doors ___ open.", "o": ["don’t", "doesn’t", "not"], "a": "don’t"}, {"p": "She ___ talk.", "o": ["doesn’t", "don’t", "no"], "a": "doesn’t"}]}, {"id": "adj", "title": "Tired, hungry, thirsty", "skill": "ADJ.FEEL", "items": [{"p": "I want food. I am ___.", "o": ["hungry", "thirsty", "tired"], "a": "hungry"}, {"p": "I want water. I am ___.", "o": ["thirsty", "hungry", "tired"], "a": "thirsty"}, {"p": "I want to sleep. I am ___.", "o": ["tired", "hungry", "thirsty"], "a": "tired"}, {"p": "They want to get married. They are in ___.", "o": ["love", "hungry", "stuck"], "a": "love"}]}, {"id": "time", "title": "For 19 hours, three months later", "skill": "PREP.TIME", "items": [{"p": "They are together ___ 19 hours.", "o": ["for", "at", "in"], "a": "for"}, {"p": "Three months ___, they get married.", "o": ["later", "late", "after"], "a": "later"}, {"p": "The elevator goes up. ___ it stops.", "o": ["Then", "Than", "The"], "a": "Then"}]}];
SD.ME = {"prompt": "The man and the woman talk for 19 hours. And you? Who do you talk to? Finish the sentence, then say it.", "before": "I talk to my", "after": "every day.", "options": ["mother", "father", "sister", "brother", "friend", "teacher"]};
