/* data.js — Neighbors (VETS Story 06). One source of truth for every practice page. */
window.SD = window.SD || {};
SD.STORY = 'story-06';
SD.NN = '06';
SD.TITLE = "Neighbors";
SD.SUB = "A married couple is unhappy. They find a clever solution.";
SD.STORY_URL = '../vets_story_06.html';
SD.ART = {};
SD.VOCAB = [{"w": "married", "pic": "💒", "gloss": "husband and wife", "s": "Jack and Ann are ___."}, {"w": "happy", "pic": "😊", "gloss": "feeling good", "s": "They are not ___ together."}, {"w": "different", "pic": "↔️", "gloss": "not the same", "s": "They are very ___."}, {"w": "smoke", "pic": "🚬", "gloss": "use cigarettes", "s": "Jack likes to ___."}, {"w": "baseball", "pic": "⚾", "gloss": "a sport with a bat and ball", "s": "Jack likes to watch ___."}, {"w": "loud", "pic": "🔊", "gloss": "with a lot of sound", "s": "Ann likes ___ music."}, {"w": "music", "pic": "🎵", "gloss": "sounds you listen to", "s": "Ann likes loud ___."}, {"w": "snores", "pic": "💤", "gloss": "makes noise when sleeping", "s": "At night, Jack ___!"}, {"w": "sleep", "pic": "🛏️", "gloss": "rest with your eyes closed", "s": "Ann can’t ___."}, {"w": "house", "pic": "🏠", "gloss": "a building where people live", "s": "Ann sees the ___ next door."}, {"w": "buys", "pic": "💵", "gloss": "pays money for", "s": "Ann ___ the house."}, {"w": "neighbors", "pic": "🏘️", "gloss": "people who live next door", "s": "Now they are ___."}];
SD.SENTS = ["Jack and Ann are married.", "But they are not happy together.", "They are very different.", "Jack likes to watch baseball and smoke.", "Ann likes loud music.", "At night, Jack snores!", "Ann can’t sleep.", "One day, Ann sees the house next door.", "It is for sale!", "Ann buys the house.", "She moves in.", "Now Ann lives in the house next to Jack.", "In his house, Jack can watch baseball, smoke, and snore.", "In her house, Ann can play loud music and sleep.", "Now Jack and Ann are married and happy!"];
SD.SOUNDS = [{"name": "i as in like", "key": "like", "words": ["like", "night", "buy", "why", "my"]}, {"name": "i as in it", "key": "it", "words": ["it", "is", "lives", "different", "in"]}, {"name": "a as in happy", "key": "happy", "words": ["Ann", "Jack", "can", "can’t", "happy"]}, {"name": "ou as in loud", "key": "loud", "words": ["loud", "house", "now", "out", "how"]}];
SD.SPELL = [{"w": "married", "hide": [1, 4]}, {"w": "happy", "hide": [1, 3]}, {"w": "different", "hide": [1, 4]}, {"w": "smoke", "hide": [2, 4]}, {"w": "baseball", "hide": [1, 4]}, {"w": "loud", "hide": [1, 2]}, {"w": "music", "hide": [1, 3]}, {"w": "snores", "hide": [1, 4]}, {"w": "sleep", "hide": [2, 3]}, {"w": "house", "hide": [1, 2]}];
SD.WRITE = ["Jack and Ann are married, but they are not happy.", "They are very different.", "Ann buys the house next door.", "She moves in.", "Now Ann is Jack’s neighbor.", "Jack can snore.", "Ann can sleep."];
SD.DICT = {"word": [{"say": "smoke", "opts": ["smoke", "smile", "soak"]}, {"say": "loud", "opts": ["loud", "load", "cloud"]}, {"say": "snores", "opts": ["snores", "stores", "scores"]}, {"say": "sleep", "opts": ["sleep", "slip", "sheep"]}, {"say": "house", "opts": ["house", "horse", "how"]}, {"say": "buys", "opts": ["buys", "boys", "bees"]}, {"say": "happy", "opts": ["happy", "hoppy", "hobby"]}, {"say": "night", "opts": ["night", "light", "nice"]}], "phrase": [{"say": "not happy together", "extra": ["sad"]}, {"say": "loud music", "extra": ["quiet"]}, {"say": "next door", "extra": ["window"]}, {"say": "for sale", "extra": ["rent"]}, {"say": "can’t sleep", "extra": ["eat"]}, {"say": "married and happy", "extra": ["single"]}], "sentence": [{"say": "Jack and Ann are married.", "extra": ["single"]}, {"say": "They are very different.", "extra": ["same"]}, {"say": "Ann likes loud music.", "extra": ["quiet"]}, {"say": "Ann buys the house next door.", "extra": ["car"]}, {"say": "In his house Jack can snore.", "extra": ["her"]}, {"say": "Now they are married and happy.", "extra": ["sad"]}]};
SD.GRAMMAR = [{"id": "can", "title": "Can / can’t", "skill": "MODAL.CAN", "items": [{"p": "In his house, Jack ___ smoke.", "o": ["can", "can’t", "cans"], "a": "can"}, {"p": "Jack snores. Ann ___ sleep.", "o": ["can’t", "can", "cans"], "a": "can’t"}, {"p": "In her house, Ann ___ play loud music.", "o": ["can", "can’t", "is can"], "a": "can"}, {"p": "Now they ___ be happy.", "o": ["can", "can’t", "cans"], "a": "can"}]}, {"id": "neg", "title": "Doesn’t / don’t", "skill": "NEG.DOES", "items": [{"p": "Ann ___ smoke.", "o": ["doesn’t", "don’t", "isn’t"], "a": "doesn’t"}, {"p": "Jack ___ like loud music.", "o": ["doesn’t", "don’t", "not"], "a": "doesn’t"}, {"p": "They ___ like the same things.", "o": ["don’t", "doesn’t", "aren’t"], "a": "don’t"}]}, {"id": "like", "title": "Likes to + verb", "skill": "LIKE.TO", "items": [{"p": "Jack likes ___ watch baseball.", "o": ["to", "for", "at"], "a": "to"}, {"p": "Ann likes ___ music.", "o": ["loud", "louds", "loudly"], "a": "loud"}, {"p": "He likes to ___.", "o": ["smoke", "smokes", "smoking"], "a": "smoke"}]}, {"id": "poss", "title": "His house, her house", "skill": "POSS", "items": [{"p": "In ___ house, Jack can snore.", "o": ["his", "her", "him"], "a": "his"}, {"p": "In ___ house, Ann can sleep.", "o": ["her", "his", "she"], "a": "her"}, {"p": "Ann is ___ neighbor.", "o": ["Jack’s", "Jack", "Jacks’"], "a": "Jack’s"}]}];
SD.ME = {"prompt": "Jack likes baseball. Ann likes loud music. And you? Finish the sentence, then say it.", "before": "I like", "after": "at home.", "options": ["baseball", "loud music", "quiet", "movies", "sleeping", "cooking"]};
