/* ============================================================
   items.js — grammar units for Mr. Toby's practice engine.

   To add a unit, copy a block and change it. Nothing else to edit.
     slug   : the web address, /readings/grammar/?u=SLUG
     skills : the tags that feed the coloured skill bars
     items  : prompt uses ___ for the blank
              answer  = the correct word
              choices = the word bank shown to the student
              skill   = which target skill this one prompt tests
   ============================================================ */
var UNITS = [
{
  slug: 'for-to-with-1',
  title: 'For, To, and With 1',
  level: '103',
  directions: 'Fill in the blank with the correct word.',
  skills: ['other-prepositions','prepositions-of-direction','infinitive-phrases'],
  items: [
    {prompt:'This backpack is ___ my little brother.', answer:'for',
     choices:['for','to','with'], skill:'other-prepositions',
     why:'We use <b>for</b> to show who receives something.'},
    {prompt:'Does your sister walk ___ school every morning?', answer:'to',
     choices:['for','to','with'], skill:'prepositions-of-direction',
     why:'We use <b>to</b> to show the direction someone moves.'},
    {prompt:'I want ___ learn more English this year.', answer:'to',
     choices:['for','to','with'], skill:'infinitive-phrases',
     why:'After a verb like <b>want</b>, we use <b>to</b> + another verb.'},
    {prompt:'She eats lunch ___ her cousins.', answer:'with',
     choices:['for','to','with'], skill:'other-prepositions',
     why:'We use <b>with</b> to show who is together.'},
    {prompt:'My family stayed in Oakland ___ three weeks.', answer:'for',
     choices:['for','to','with'], skill:'other-prepositions',
     why:'We use <b>for</b> with a length of time.'},
    {prompt:'Marco buys flowers ___ his grandmother.', answer:'for',
     choices:['for','to','with'], skill:'other-prepositions',
     why:'We use <b>for</b> to show who receives something.'},
    {prompt:'These new books are ___ the ELD class.', answer:'for',
     choices:['for','to','with'], skill:'other-prepositions',
     why:'We use <b>for</b> to show who something is meant for.'},
    {prompt:'I take the bus ___ the library after school.', answer:'to',
     choices:['for','to','with'], skill:'prepositions-of-direction',
     why:'We use <b>to</b> to show where someone is going.'},
    {prompt:'We do not write ___ red pens on the test.', answer:'with',
     choices:['for','to','with'], skill:'other-prepositions',
     why:'We use <b>with</b> to show the tool someone uses.'},
    {prompt:'He plays basketball ___ his friends on Saturday.', answer:'with',
     choices:['for','to','with'], skill:'other-prepositions',
     why:'We use <b>with</b> to show who is together.'},
    {prompt:'My mother needs ___ call the doctor today.', answer:'to',
     choices:['for','to','with'], skill:'infinitive-phrases',
     why:'After a verb like <b>need</b>, we use <b>to</b> + another verb.'},
    {prompt:'They study hard ___ the science quiz.', answer:'for',
     choices:['for','to','with'], skill:'other-prepositions',
     why:'We use <b>for</b> to show the reason or purpose.'}
  ]
},
{
  slug: 'in-on-at-time',
  title: 'In, On, and At: Time',
  level: '103',
  directions: 'Fill in the blank with the correct word.',
  skills: ['prepositions-of-time'],
  items: [
    {prompt:'Our class starts ___ 8:30 in the morning.', answer:'at',
     choices:['in','on','at'], skill:'prepositions-of-time',
     why:'We use <b>at</b> with a clock time.'},
    {prompt:'My birthday is ___ March.', answer:'in',
     choices:['in','on','at'], skill:'prepositions-of-time',
     why:'We use <b>in</b> with a month.'},
    {prompt:'We have a test ___ Friday.', answer:'on',
     choices:['in','on','at'], skill:'prepositions-of-time',
     why:'We use <b>on</b> with a day of the week.'},
    {prompt:'She came to San Francisco ___ 2023.', answer:'in',
     choices:['in','on','at'], skill:'prepositions-of-time',
     why:'We use <b>in</b> with a year.'},
    {prompt:'The library closes ___ six o\'clock.', answer:'at',
     choices:['in','on','at'], skill:'prepositions-of-time',
     why:'We use <b>at</b> with a clock time.'},
    {prompt:'I visit my aunt ___ the weekend.', answer:'on',
     choices:['in','on','at'], skill:'prepositions-of-time',
     why:'In American English we use <b>on</b> with the weekend.'},
    {prompt:'It rains a lot here ___ the winter.', answer:'in',
     choices:['in','on','at'], skill:'prepositions-of-time',
     why:'We use <b>in</b> with a season.'},
    {prompt:'We eat dinner ___ night.', answer:'at',
     choices:['in','on','at'], skill:'prepositions-of-time',
     why:'We say <b>at night</b>, but <b>in the morning</b>.'},
    {prompt:'My brother was born ___ September 14.', answer:'on',
     choices:['in','on','at'], skill:'prepositions-of-time',
     why:'We use <b>on</b> with a full date.'},
    {prompt:'She studies English ___ the afternoon.', answer:'in',
     choices:['in','on','at'], skill:'prepositions-of-time',
     why:'We use <b>in</b> with the morning, the afternoon, the evening.'}
  ]
}
,
{
  slug: 'subject-verb-1',
  title: 'Subject and Verb Agreement 1',
  level: '103',
  directions: 'Choose the verb that matches the subject.',
  skills: ['subject-verb-agreement'],
  items: [
    {prompt:'My cousin ___ in Daly City.', answer:'lives',
     choices:['live','lives'], skill:'subject-verb-agreement',
     why:'One person (he, she, my cousin) takes the verb with <b>-s</b>.'},
    {prompt:'My two brothers ___ soccer after school.', answer:'play',
     choices:['play','plays'], skill:'subject-verb-agreement',
     why:'More than one person takes the verb with <b>no -s</b>.'},
    {prompt:'The students ___ tired on Monday morning.', answer:'are',
     choices:['is','are'], skill:'subject-verb-agreement',
     why:'<b>Students</b> is plural, so we use <b>are</b>.'},
    {prompt:'My teacher ___ from San Francisco.', answer:'is',
     choices:['is','are'], skill:'subject-verb-agreement',
     why:'One person takes <b>is</b>.'},
    {prompt:'She ___ three sisters in Guatemala.', answer:'has',
     choices:['have','has'], skill:'subject-verb-agreement',
     why:'With he, she, or it we use <b>has</b>.'},
    {prompt:'We ___ English class in the morning.', answer:'have',
     choices:['have','has'], skill:'subject-verb-agreement',
     why:'With I, you, we, or they we use <b>have</b>.'},
    {prompt:'My friend and I ___ lunch together every day.', answer:'eat',
     choices:['eat','eats'], skill:'subject-verb-agreement',
     why:'<b>My friend and I</b> means two people, so no <b>-s</b>.'},
    {prompt:'The bus ___ late almost every morning.', answer:'comes',
     choices:['come','comes'], skill:'subject-verb-agreement',
     why:'<b>The bus</b> is one thing, so the verb takes <b>-s</b>.'},
    {prompt:'My parents ___ Arabic at home.', answer:'speak',
     choices:['speak','speaks'], skill:'subject-verb-agreement',
     why:'<b>Parents</b> is plural, so no <b>-s</b> on the verb.'},
    {prompt:'It ___ a lot in San Francisco in the winter.', answer:'rains',
     choices:['rain','rains'], skill:'subject-verb-agreement',
     why:'With <b>it</b> the verb takes <b>-s</b>.'},
    {prompt:'My sister ___ not like cold weather.', answer:'does',
     choices:['do','does'], skill:'subject-verb-agreement',
     why:'With he, she, or it we use <b>does not</b>.'},
    {prompt:'They ___ not have homework tonight.', answer:'do',
     choices:['do','does'], skill:'subject-verb-agreement',
     why:'With I, you, we, or they we use <b>do not</b>.'}
  ]
},
{
  slug: 'and-but-so',
  title: 'And, But, So',
  level: '103',
  directions: 'Choose the word that joins the two parts of the sentence.',
  skills: ['conjunctions'],
  items: [
    {prompt:'I studied all weekend, ___ I passed the test.', answer:'so',
     choices:['and','but','so'], skill:'conjunctions',
     why:'<b>So</b> shows the result of the first part.'},
    {prompt:'She speaks Spanish, ___ she is learning English.', answer:'and',
     choices:['and','but','so'], skill:'conjunctions',
     why:'<b>And</b> adds one idea to another.'},
    {prompt:'I wanted to go to the park, ___ it was raining.', answer:'but',
     choices:['and','but','so'], skill:'conjunctions',
     why:'<b>But</b> shows a surprise or a difference.'},
    {prompt:'The bus was late, ___ I missed first period.', answer:'so',
     choices:['and','but','so'], skill:'conjunctions',
     why:'<b>So</b> shows what happened because of the first part.'},
    {prompt:'My brother plays basketball, ___ I play soccer.', answer:'and',
     choices:['and','but','so'], skill:'conjunctions',
     why:'<b>And</b> joins two equal ideas.'},
    {prompt:'I like the beach, ___ the water here is too cold.', answer:'but',
     choices:['and','but','so'], skill:'conjunctions',
     why:'<b>But</b> shows the two ideas do not match.'},
    {prompt:'We were hungry, ___ we walked to the cafeteria.', answer:'so',
     choices:['and','but','so'], skill:'conjunctions',
     why:'<b>So</b> shows the result.'},
    {prompt:'She is new at Galileo, ___ she already has many friends.', answer:'but',
     choices:['and','but','so'], skill:'conjunctions',
     why:'<b>But</b> shows something surprising.'},
    {prompt:'I finished my homework, ___ I went to sleep early.', answer:'so',
     choices:['and','but','so'], skill:'conjunctions',
     why:'<b>So</b> shows what happened next because of the first part.'},
    {prompt:'My mother works at night, ___ my father works in the morning.', answer:'and',
     choices:['and','but','so'], skill:'conjunctions',
     why:'<b>And</b> joins two ideas that go together.'},
    {prompt:'The movie was long, ___ it was very good.', answer:'but',
     choices:['and','but','so'], skill:'conjunctions',
     why:'<b>But</b> shows a difference between the two ideas.'},
    {prompt:'I forgot my jacket, ___ I was cold all day.', answer:'so',
     choices:['and','but','so'], skill:'conjunctions',
     why:'<b>So</b> shows the result of forgetting the jacket.'}
  ]
},
{
  slug: 'commas-1',
  title: 'Commas 1: Lists and Joining Sentences',
  level: '103',
  directions: 'Choose the correct punctuation for the blank.',
  skills: ['commas','comma-splices'],
  items: [
    {prompt:'I bought apples, bananas ___ oranges at the store.', answer:', and',
     choices:[', and','and',', '], skill:'commas',
     why:'In a list, we put a comma before the last <b>and</b>.'},
    {prompt:'She studies math, science ___ art this year.', answer:', and',
     choices:[', and','and',', '], skill:'commas',
     why:'The last item in a list takes <b>, and</b>.'},
    {prompt:'I was tired ___ I finished my homework anyway.', answer:', but',
     choices:[', but','but',' but,'], skill:'comma-splices',
     why:'When two full sentences join, put the comma <b>before</b> the joining word.'},
    {prompt:'The test was hard ___ I studied for a long time.', answer:', so',
     choices:[', so','so',' so,'], skill:'comma-splices',
     why:'Two full sentences joined by <b>so</b> need a comma before it.'},
    {prompt:'My family is from Vietnam ___ we moved here in 2023.', answer:', and',
     choices:[', and','and',' and,'], skill:'comma-splices',
     why:'Both halves are full sentences, so use <b>, and</b>.'},
    {prompt:'We packed water, snacks ___ a map for the trip.', answer:', and',
     choices:[', and','and',', '], skill:'commas',
     why:'The last item in a list takes <b>, and</b>.'},
    {prompt:'I like this school ___ the teachers are kind.', answer:', and',
     choices:[', and','and',' and,'], skill:'comma-splices',
     why:'Two full sentences need a comma before the joining word.'},
    {prompt:'He speaks Cantonese, Mandarin ___ English.', answer:', and',
     choices:[', and','and',', '], skill:'commas',
     why:'Use a comma before the final <b>and</b> in a list.'},
    {prompt:'The bus came late ___ I still arrived on time.', answer:', but',
     choices:[', but','but',' but,'], skill:'comma-splices',
     why:'Put the comma before <b>but</b> when it joins two sentences.'},
    {prompt:'She wants to be a nurse ___ she studies biology every night.', answer:', so',
     choices:[', so','so',' so,'], skill:'comma-splices',
     why:'Use <b>, so</b> to join two full sentences.'}
  ]
}
,
/* ============================================================
   NEW FORMAT units (same question types as the Grammar Checks).
   See the note at the top of grammar/index.html's item logic.
   ============================================================ */
{
  slug: 'articles-1',
  title: 'A, An, The, or Nothing 1',
  level: '101',
  directions: 'Fill in the blanks. Some blanks need NO word. Choose \u2205 for those.',
  skills: ['articles'],
  items: [
    {type:'slots', skill:'articles', empty:true, opts:['a','an','the'],
     text:'I have {a} dog. {the} dog is {} brown.',
     why:'Use <b>a</b> the first time you talk about something. Use <b>the</b> after that. Use no word before a color alone.'},
    {type:'slots', skill:'articles', empty:true, opts:['a','an','the'],
     text:'Can I have {an} orange, please?',
     why:'Use <b>an</b> before a vowel sound: an orange, an apple, an egg.'},
    {type:'slots', skill:'articles', empty:true, opts:['a','an','the'],
     text:'The bus is late. I wait {an} hour every day!',
     why:'<b>Hour</b> starts with a vowel sound (the h is silent), so we say <b>an</b> hour.'},
    {type:'slots', skill:'articles', empty:true, opts:['a','an','the'],
     text:'My sister loves {} cats, but she does not like {} dogs.',
     why:'When we talk about all cats or all dogs, we use no word: I love cats.'},
    {type:'slots', skill:'articles', empty:true, opts:['a','an','the'],
     text:'We play {} soccer after {} school.',
     why:'No word before sports (soccer, basketball) and in <b>after school</b>, <b>go to school</b>.'},
    {type:'slots', skill:'articles', empty:true, opts:['a','an','the'],
     text:'Look at {the} moon! It is so bright tonight.',
     why:'There is only one moon, so we say <b>the</b> moon, <b>the</b> sun, <b>the</b> sky.'},
    {type:'slots', skill:'articles', dir:'Tap the underlined words. Fix the ones that are wrong.',
     text:'I ate [a apple>an apple:a apple,an apple,the apples,apple] for lunch.',
     why:'<b>Apple</b> starts with a vowel sound, so we say <b>an</b> apple.'},
    {type:'slots', skill:'articles', dir:'Tap the underlined words. Fix the ones that are wrong.',
     text:'My aunt is [doctor>a doctor:doctor,a doctor,an doctor,the doctors]. She works at night.',
     why:'Use <b>a</b> or <b>an</b> before a job: She is <b>a</b> doctor. He is <b>an</b> engineer.'},
    {type:'slots', skill:'articles', empty:true, opts:['a','an','the'],
     text:'There is {a} cat in our yard. {the} cat is {} hungry.',
     why:'First time: <b>a</b> cat. Second time: <b>the</b> cat. No word before <b>hungry</b>.'},
    {type:'slots', skill:'articles', empty:true, opts:['a','an','the'],
     text:'Omar is {an} honest student. He always tells {the} truth.',
     why:'<b>Honest</b> starts with a vowel sound (silent h), so <b>an</b> honest. We say <b>tell the truth</b>.'}
  ]
},
{
  slug: 'joining-sentences-1',
  title: 'Joining Sentences 1',
  level: '101/103',
  directions: 'Combine the sentences into one sentence. Use the joining word.',
  skills: ['compound-subjects','compound-predicates','compound-sentences'],
  items: [
    {type:'write', skill:'compound-subjects', words:['and'],
     prompt:'Mario is tired. Luis is tired.',
     accept:['Mario and Luis are tired.','Luis and Mario are tired.'],
     why:'Two people doing the same thing: join them with <b>and</b>. Two people means <b>are</b>, not is.'},
    {type:'write', skill:'compound-subjects', words:['and'],
     prompt:'My mom works at night. My dad works at night.',
     accept:['My mom and my dad work at night.','My mom and dad work at night.','My dad and my mom work at night.','My dad and mom work at night.'],
     why:'Two people is plural, so the verb loses the <b>-s</b>: works \u2192 <b>work</b>.'},
    {type:'write', skill:'compound-predicates', words:['and'],
     prompt:'Kenji opens his book. Kenji reads the first page.',
     accept:['Kenji opens his book and reads the first page.'],
     why:'Same person, two actions. Say the name once and join the actions with <b>and</b>. No comma.'},
    {type:'write', skill:'compound-predicates', words:['and'],
     prompt:'Birds build nests. Birds lay eggs.',
     accept:['Birds build nests and lay eggs.'],
     why:'Same subject, two actions: <b>Birds build nests and lay eggs.</b>'},
    {type:'write', skill:'compound-sentences', words:['and','but','so'],
     prompt:'I was hungry. I made a sandwich.',
     accept:['I was hungry, so I made a sandwich.'],
     why:'The second idea is the result, so use <b>so</b>. Put a comma before <b>so</b> when it joins two full sentences.'},
    {type:'write', skill:'compound-sentences', words:['and','but','so'],
     prompt:'Rosa likes math. She does not like science.',
     accept:['Rosa likes math, but she does not like science.'],
     why:'The ideas are different, so use <b>but</b>. Put a comma before <b>but</b>.'},
    {type:'write', skill:'compound-sentences', words:['and','but','so'],
     prompt:'It was cold. We wore jackets.',
     accept:['It was cold, so we wore jackets.'],
     why:'Cold is the reason, jackets are the result: use <b>, so</b>.'},
    {type:'order', skill:'compound-sentences', dir:'Put the words in order to make one sentence.',
     tiles:['late,','the','was','bus','so','walked','I'], post:'.',
     accept:['The bus was late, so I walked.'],
     why:'Sentence one, then a comma, then <b>so</b>, then sentence two.'}
  ]
}
];
