/* ============================================================
   items.js — grammar units for Mr. Toby's practice engine.

   To add a unit, copy a block and change it. Nothing else to edit.
     slug   : the web address, /readings/grammar/?u=SLUG
     skills : the tags that feed the coloured skill bars
     items  : prompt uses ___ for the blank
              answer  = the correct word
              choices = the word bank shown to the student
              skill   = which target skill this one prompt tests
   ============================================================ */
var UNITS = [
{
  slug: 'for-to-with-1',
  title: 'For, To, and With 1',
  level: '103',
  directions: 'Fill in the blank with the correct word.',
  skills: ['other-prepositions','prepositions-of-direction','infinitive-phrases'],
  items: [
    {prompt:'This backpack is ___ my little brother.', answer:'for',
     choices:['for','to','with'], skill:'other-prepositions',
     why:'We use <b>for</b> to show who receives something.'},
    {prompt:'Does your sister walk ___ school every morning?', answer:'to',
     choices:['for','to','with'], skill:'prepositions-of-direction',
     why:'We use <b>to</b> to show the direction someone moves.'},
    {prompt:'I want ___ learn more English this year.', answer:'to',
     choices:['for','to','with'], skill:'infinitive-phrases',
     why:'After a verb like <b>want</b>, we use <b>to</b> + another verb.'},
    {prompt:'She eats lunch ___ her cousins.', answer:'with',
     choices:['for','to','with'], skill:'other-prepositions',
     why:'We use <b>with</b> to show who is together.'},
    {prompt:'My family stayed in Oakland ___ three weeks.', answer:'for',
     choices:['for','to','with'], skill:'other-prepositions',
     why:'We use <b>for</b> with a length of time.'},
    {prompt:'Marco buys flowers ___ his grandmother.', answer:'for',
     choices:['for','to','with'], skill:'other-prepositions',
     why:'We use <b>for</b> to show who receives something.'},
    {prompt:'These new books are ___ the ELD class.', answer:'for',
     choices:['for','to','with'], skill:'other-prepositions',
     why:'We use <b>for</b> to show who something is meant for.'},
    {prompt:'I take the bus ___ the library after school.', answer:'to',
     choices:['for','to','with'], skill:'prepositions-of-direction',
     why:'We use <b>to</b> to show where someone is going.'},
    {prompt:'We do not write ___ red pens on the test.', answer:'with',
     choices:['for','to','with'], skill:'other-prepositions',
     why:'We use <b>with</b> to show the tool someone uses.'},
    {prompt:'He plays basketball ___ his friends on Saturday.', answer:'with',
     choices:['for','to','with'], skill:'other-prepositions',
     why:'We use <b>with</b> to show who is together.'},
    {prompt:'My mother needs ___ call the doctor today.', answer:'to',
     choices:['for','to','with'], skill:'infinitive-phrases',
     why:'After a verb like <b>need</b>, we use <b>to</b> + another verb.'},
    {prompt:'They study hard ___ the science quiz.', answer:'for',
     choices:['for','to','with'], skill:'other-prepositions',
     why:'We use <b>for</b> to show the reason or purpose.'}
  ]
},
{
  slug: 'in-on-at-time',
  title: 'In, On, and At: Time',
  level: '103',
  directions: 'Fill in the blank with the correct word.',
  skills: ['prepositions-of-time'],
  items: [
    {prompt:'Our class starts ___ 8:30 in the morning.', answer:'at',
     choices:['in','on','at'], skill:'prepositions-of-time',
     why:'We use <b>at</b> with a clock time.'},
    {prompt:'My birthday is ___ March.', answer:'in',
     choices:['in','on','at'], skill:'prepositions-of-time',
     why:'We use <b>in</b> with a month.'},
    {prompt:'We have a test ___ Friday.', answer:'on',
     choices:['in','on','at'], skill:'prepositions-of-time',
     why:'We use <b>on</b> with a day of the week.'},
    {prompt:'She came to San Francisco ___ 2023.', answer:'in',
     choices:['in','on','at'], skill:'prepositions-of-time',
     why:'We use <b>in</b> with a year.'},
    {prompt:'The library closes ___ six o\'clock.', answer:'at',
     choices:['in','on','at'], skill:'prepositions-of-time',
     why:'We use <b>at</b> with a clock time.'},
    {prompt:'I visit my aunt ___ the weekend.', answer:'on',
     choices:['in','on','at'], skill:'prepositions-of-time',
     why:'In American English we use <b>on</b> with the weekend.'},
    {prompt:'It rains a lot here ___ the winter.', answer:'in',
     choices:['in','on','at'], skill:'prepositions-of-time',
     why:'We use <b>in</b> with a season.'},
    {prompt:'We eat dinner ___ night.', answer:'at',
     choices:['in','on','at'], skill:'prepositions-of-time',
     why:'We say <b>at night</b>, but <b>in the morning</b>.'},
    {prompt:'My brother was born ___ September 14.', answer:'on',
     choices:['in','on','at'], skill:'prepositions-of-time',
     why:'We use <b>on</b> with a full date.'},
    {prompt:'She studies English ___ the afternoon.', answer:'in',
     choices:['in','on','at'], skill:'prepositions-of-time',
     why:'We use <b>in</b> with the morning, the afternoon, the evening.'}
  ]
}
,
{
  slug: 'subject-verb-1',
  title: 'Subject and Verb Agreement 1',
  level: '103',
  directions: 'Choose the verb that matches the subject.',
  skills: ['subject-verb-agreement'],
  items: [
    {prompt:'My cousin ___ in Daly City.', answer:'lives',
     choices:['live','lives'], skill:'subject-verb-agreement',
     why:'One person (he, she, my cousin) takes the verb with <b>-s</b>.'},
    {prompt:'My two brothers ___ soccer after school.', answer:'play',
     choices:['play','plays'], skill:'subject-verb-agreement',
     why:'More than one person takes the verb with <b>no -s</b>.'},
    {prompt:'The students ___ tired on Monday morning.', answer:'are',
     choices:['is','are'], skill:'subject-verb-agreement',
     why:'<b>Students</b> is plural, so we use <b>are</b>.'},
    {prompt:'My teacher ___ from San Francisco.', answer:'is',
     choices:['is','are'], skill:'subject-verb-agreement',
     why:'One person takes <b>is</b>.'},
    {prompt:'She ___ three sisters in Guatemala.', answer:'has',
     choices:['have','has'], skill:'subject-verb-agreement',
     why:'With he, she, or it we use <b>has</b>.'},
    {prompt:'We ___ English class in the morning.', answer:'have',
     choices:['have','has'], skill:'subject-verb-agreement',
     why:'With I, you, we, or they we use <b>have</b>.'},
    {prompt:'My friend and I ___ lunch together every day.', answer:'eat',
     choices:['eat','eats'], skill:'subject-verb-agreement',
     why:'<b>My friend and I</b> means two people, so no <b>-s</b>.'},
    {prompt:'The bus ___ late almost every morning.', answer:'comes',
     choices:['come','comes'], skill:'subject-verb-agreement',
     why:'<b>The bus</b> is one thing, so the verb takes <b>-s</b>.'},
    {prompt:'My parents ___ Arabic at home.', answer:'speak',
     choices:['speak','speaks'], skill:'subject-verb-agreement',
     why:'<b>Parents</b> is plural, so no <b>-s</b> on the verb.'},
    {prompt:'It ___ a lot in San Francisco in the winter.', answer:'rains',
     choices:['rain','rains'], skill:'subject-verb-agreement',
     why:'With <b>it</b> the verb takes <b>-s</b>.'},
    {prompt:'My sister ___ not like cold weather.', answer:'does',
     choices:['do','does'], skill:'subject-verb-agreement',
     why:'With he, she, or it we use <b>does not</b>.'},
    {prompt:'They ___ not have homework tonight.', answer:'do',
     choices:['do','does'], skill:'subject-verb-agreement',
     why:'With I, you, we, or they we use <b>do not</b>.'}
  ]
},
{
  slug: 'and-but-so',
  title: 'And, But, So',
  level: '103',
  directions: 'Choose the word that joins the two parts of the sentence.',
  skills: ['conjunctions'],
  items: [
    {prompt:'I studied all weekend, ___ I passed the test.', answer:'so',
     choices:['and','but','so'], skill:'conjunctions',
     why:'<b>So</b> shows the result of the first part.'},
    {prompt:'She speaks Spanish, ___ she is learning English.', answer:'and',
     choices:['and','but','so'], skill:'conjunctions',
     why:'<b>And</b> adds one idea to another.'},
    {prompt:'I wanted to go to the park, ___ it was raining.', answer:'but',
     choices:['and','but','so'], skill:'conjunctions',
     why:'<b>But</b> shows a surprise or a difference.'},
    {prompt:'The bus was late, ___ I missed first period.', answer:'so',
     choices:['and','but','so'], skill:'conjunctions',
     why:'<b>So</b> shows what happened because of the first part.'},
    {prompt:'My brother plays basketball, ___ I play soccer.', answer:'and',
     choices:['and','but','so'], skill:'conjunctions',
     why:'<b>And</b> joins two equal ideas.'},
    {prompt:'I like the beach, ___ the water here is too cold.', answer:'but',
     choices:['and','but','so'], skill:'conjunctions',
     why:'<b>But</b> shows the two ideas do not match.'},
    {prompt:'We were hungry, ___ we walked to the cafeteria.', answer:'so',
     choices:['and','but','so'], skill:'conjunctions',
     why:'<b>So</b> shows the result.'},
    {prompt:'She is new at Galileo, ___ she already has many friends.', answer:'but',
     choices:['and','but','so'], skill:'conjunctions',
     why:'<b>But</b> shows something surprising.'},
    {prompt:'I finished my homework, ___ I went to sleep early.', answer:'so',
     choices:['and','but','so'], skill:'conjunctions',
     why:'<b>So</b> shows what happened next because of the first part.'},
    {prompt:'My mother works at night, ___ my father works in the morning.', answer:'and',
     choices:['and','but','so'], skill:'conjunctions',
     why:'<b>And</b> joins two ideas that go together.'},
    {prompt:'The movie was long, ___ it was very good.', answer:'but',
     choices:['and','but','so'], skill:'conjunctions',
     why:'<b>But</b> shows a difference between the two ideas.'},
    {prompt:'I forgot my jacket, ___ I was cold all day.', answer:'so',
     choices:['and','but','so'], skill:'conjunctions',
     why:'<b>So</b> shows the result of forgetting the jacket.'}
  ]
},
{
  slug: 'commas-1',
  title: 'Commas 1: Lists and Joining Sentences',
  level: '103',
  directions: 'Choose the correct punctuation for the blank.',
  skills: ['commas','comma-splices'],
  items: [
    {prompt:'I bought apples, bananas ___ oranges at the store.', answer:', and',
     choices:[', and','and',', '], skill:'commas',
     why:'In a list, we put a comma before the last <b>and</b>.'},
    {prompt:'She studies math, science ___ art this year.', answer:', and',
     choices:[', and','and',', '], skill:'commas',
     why:'The last item in a list takes <b>, and</b>.'},
    {prompt:'I was tired ___ I finished my homework anyway.', answer:', but',
     choices:[', but','but',' but,'], skill:'comma-splices',
     why:'When two full sentences join, put the comma <b>before</b> the joining word.'},
    {prompt:'The test was hard ___ I studied for a long time.', answer:', so',
     choices:[', so','so',' so,'], skill:'comma-splices',
     why:'Two full sentences joined by <b>so</b> need a comma before it.'},
    {prompt:'My family is from Vietnam ___ we moved here in 2023.', answer:', and',
     choices:[', and','and',' and,'], skill:'comma-splices',
     why:'Both halves are full sentences, so use <b>, and</b>.'},
    {prompt:'We packed water, snacks ___ a map for the trip.', answer:', and',
     choices:[', and','and',', '], skill:'commas',
     why:'The last item in a list takes <b>, and</b>.'},
    {prompt:'I like this school ___ the teachers are kind.', answer:', and',
     choices:[', and','and',' and,'], skill:'comma-splices',
     why:'Two full sentences need a comma before the joining word.'},
    {prompt:'He speaks Cantonese, Mandarin ___ English.', answer:', and',
     choices:[', and','and',', '], skill:'commas',
     why:'Use a comma before the final <b>and</b> in a list.'},
    {prompt:'The bus came late ___ I still arrived on time.', answer:', but',
     choices:[', but','but',' but,'], skill:'comma-splices',
     why:'Put the comma before <b>but</b> when it joins two sentences.'},
    {prompt:'She wants to be a nurse ___ she studies biology every night.', answer:', so',
     choices:[', so','so',' so,'], skill:'comma-splices',
     why:'Use <b>, so</b> to join two full sentences.'}
  ]
}
,
/* ============================================================
   NEW FORMAT units (same question types as the Grammar Checks).
   See the note at the top of grammar/index.html's item logic.
   ============================================================ */
{
  slug: 'articles-1',
  title: 'A, An, The, or Nothing 1',
  level: '101',
  directions: 'Fill in the blanks. Some blanks need NO word. Choose \u2205 for those.',
  skills: ['articles'],
  items: [
    {type:'slots', skill:'articles', empty:true, opts:['a','an','the'],
     text:'I have {a} dog. {the} dog is {} brown.',
     why:'Use <b>a</b> the first time you talk about something. Use <b>the</b> after that. Use no word before a color alone.'},
    {type:'slots', skill:'articles', empty:true, opts:['a','an','the'],
     text:'Can I have {an} orange, please?',
     why:'Use <b>an</b> before a vowel sound: an orange, an apple, an egg.'},
    {type:'slots', skill:'articles', empty:true, opts:['a','an','the'],
     text:'The bus is late. I wait {an} hour every day!',
     why:'<b>Hour</b> starts with a vowel sound (the h is silent), so we say <b>an</b> hour.'},
    {type:'slots', skill:'articles', empty:true, opts:['a','an','the'],
     text:'My sister loves {} cats, but she does not like {} dogs.',
     why:'When we talk about all cats or all dogs, we use no word: I love cats.'},
    {type:'slots', skill:'articles', empty:true, opts:['a','an','the'],
     text:'We play {} soccer after {} school.',
     why:'No word before sports (soccer, basketball) and in <b>after school</b>, <b>go to school</b>.'},
    {type:'slots', skill:'articles', empty:true, opts:['a','an','the'],
     text:'Look at {the} moon! It is so bright tonight.',
     why:'There is only one moon, so we say <b>the</b> moon, <b>the</b> sun, <b>the</b> sky.'},
    {type:'slots', skill:'articles', dir:'Tap the underlined words. Fix the ones that are wrong.',
     text:'I ate [a apple>an apple:a apple,an apple,the apples,apple] for lunch.',
     why:'<b>Apple</b> starts with a vowel sound, so we say <b>an</b> apple.'},
    {type:'slots', skill:'articles', dir:'Tap the underlined words. Fix the ones that are wrong.',
     text:'My aunt is [doctor>a doctor:doctor,a doctor,an doctor,the doctors]. She works at night.',
     why:'Use <b>a</b> or <b>an</b> before a job: She is <b>a</b> doctor. He is <b>an</b> engineer.'},
    {type:'slots', skill:'articles', empty:true, opts:['a','an','the'],
     text:'There is {a} cat in our yard. {the} cat is {} hungry.',
     why:'First time: <b>a</b> cat. Second time: <b>the</b> cat. No word before <b>hungry</b>.'},
    {type:'slots', skill:'articles', empty:true, opts:['a','an','the'],
     text:'Omar is {an} honest student. He always tells {the} truth.',
     why:'<b>Honest</b> starts with a vowel sound (silent h), so <b>an</b> honest. We say <b>tell the truth</b>.'}
  ]
},
{
  slug: 'joining-sentences-1',
  title: 'Joining Sentences 1',
  level: '101/103',
  directions: 'Combine the sentences into one sentence. Use the joining word.',
  skills: ['compound-subjects','compound-predicates','compound-sentences'],
  items: [
    {type:'write', skill:'compound-subjects', words:['and'],
     prompt:'Mario is tired. Luis is tired.',
     accept:['Mario and Luis are tired.','Luis and Mario are tired.'],
     why:'Two people doing the same thing: join them with <b>and</b>. Two people means <b>are</b>, not is.'},
    {type:'write', skill:'compound-subjects', words:['and'],
     prompt:'My mom works at night. My dad works at night.',
     accept:['My mom and my dad work at night.','My mom and dad work at night.','My dad and my mom work at night.','My dad and mom work at night.'],
     why:'Two people is plural, so the verb loses the <b>-s</b>: works \u2192 <b>work</b>.'},
    {type:'write', skill:'compound-predicates', words:['and'],
     prompt:'Kenji opens his book. Kenji reads the first page.',
     accept:['Kenji opens his book and reads the first page.'],
     why:'Same person, two actions. Say the name once and join the actions with <b>and</b>. No comma.'},
    {type:'write', skill:'compound-predicates', words:['and'],
     prompt:'Birds build nests. Birds lay eggs.',
     accept:['Birds build nests and lay eggs.'],
     why:'Same subject, two actions: <b>Birds build nests and lay eggs.</b>'},
    {type:'write', skill:'compound-sentences', words:['and','but','so'],
     prompt:'I was hungry. I made a sandwich.',
     accept:['I was hungry, so I made a sandwich.'],
     why:'The second idea is the result, so use <b>so</b>. Put a comma before <b>so</b> when it joins two full sentences.'},
    {type:'write', skill:'compound-sentences', words:['and','but','so'],
     prompt:'Rosa likes math. She does not like science.',
     accept:['Rosa likes math, but she does not like science.'],
     why:'The ideas are different, so use <b>but</b>. Put a comma before <b>but</b>.'},
    {type:'write', skill:'compound-sentences', words:['and','but','so'],
     prompt:'It was cold. We wore jackets.',
     accept:['It was cold, so we wore jackets.'],
     why:'Cold is the reason, jackets are the result: use <b>, so</b>.'},
    {type:'order', skill:'compound-sentences', dir:'Put the words in order to make one sentence.',
     tiles:['late,','the','was','bus','so','walked','I'], post:'.',
     accept:['The bus was late, so I walked.'],
     why:'Sentence one, then a comma, then <b>so</b>, then sentence two.'}
  ]
}
,
/* ============================================================
   Units 8-17 (Sept 28): built from the gaps in the Quill
   diagnostic reports. Skill names match the Grammar Checks.
   ============================================================ */
{
  slug: 'plurals-possessives-1',
  title: 'Plurals and Possessives 1',
  level: '101',
  directions: 'Tap the underlined words. Fix the ones that are wrong.',
  skills: ['plurals-possessives-pronouns'],
  items: [
    {type:'slots', skill:'plurals-possessives-pronouns',
     text:'I have two [brother>brothers:brother,brothers,brother\'s,brotheres] and one sister.',
     why:'More than one: add <b>-s</b>. One brother, two brother<b>s</b>.'},
    {type:'slots', skill:'plurals-possessives-pronouns',
     text:'Three [man>men:man,mans,men,mens] are waiting for the bus.',
     why:'Some words change inside: one man, two <b>men</b>. One woman, two <b>women</b>.'},
    {type:'slots', skill:'plurals-possessives-pronouns',
     text:'The [child>children:child,childs,children,childrens] are playing in the park.',
     why:'One child, two <b>children</b>. Never "childs."'},
    {type:'slots', skill:'plurals-possessives-pronouns',
     text:'People have thirty-two [tooth>teeth:tooth,tooths,teeth,teeths].',
     why:'One tooth, two <b>teeth</b>. One foot, two <b>feet</b>.'},
    {type:'slots', skill:'plurals-possessives-pronouns',
     text:'We need three [box>boxes:box,boxs,boxes,boxies] for the books.',
     why:'After <b>x, s, sh, ch</b>, add <b>-es</b>: box\u2192box<b>es</b>, bus\u2192bus<b>es</b>.'},
    {type:'slots', skill:'plurals-possessives-pronouns',
     text:'There are two big [city>cities:city,citys,cities,cityes] on the map.',
     why:'Consonant + <b>y</b>: change y to <b>ies</b>. city\u2192cit<b>ies</b>, baby\u2192bab<b>ies</b>.'},
    {type:'slots', skill:'plurals-possessives-pronouns', dir:'Choose the best word for the blank.',
     opts:["Maria's","Marias","Maria","Marias'"],
     text:"This is {Maria's} backpack.",
     why:"To show who owns something, add <b>'s</b>: Maria<b>'s</b> backpack."},
    {type:'slots', skill:'plurals-possessives-pronouns', dir:'Fill in each blank. You can use a word more than once.',
     opts:['his','her','their','its'],
     text:'Sam loves {his} dog. Lina loves {her} cat. The kids love {their} teacher.',
     why:'A boy: <b>his</b>. A girl: <b>her</b>. Two or more people: <b>their</b>.'},
    {type:'slots', skill:'plurals-possessives-pronouns', distinct:true,
     dir:'There are two correct answers. Use a different correct answer in each blank.',
     opts:["Ali's pen","his pen","his","the pen of Ali","he pen","Ali pen"],
     text:"This pen belongs to Ali. It is {Ali's pen/his pen/his}. This pen belongs to Ali. It is {Ali's pen/his pen/his}.",
     why:"All three are right: <b>Ali's pen</b>, <b>his pen</b>, or just <b>his</b>."},
    {type:'order', skill:'plurals-possessives-pronouns', dir:'Put the words in the correct order.',
     tiles:["room","is","brother's","This","my"], post:'.',
     accept:["This is my brother's room."],
     why:"Owner + <b>'s</b> + the thing: my brother<b>'s</b> room."}
  ]
},
{
  slug: 'questions-negatives-1',
  title: 'Questions and Negatives 1',
  level: '101',
  directions: 'Choose the best word for each blank.',
  skills: ['negation-and-questions'],
  items: [
    {type:'slots', skill:'negation-and-questions', opts:['do','does','is','are'],
     text:'{does} your brother play soccer?',
     why:'He / she / it + action verb: <b>Does</b> he play? Then the verb has no -s.'},
    {type:'slots', skill:'negation-and-questions', opts:['do','does','is','are'],
     text:'{are} you hungry?',
     why:'<b>Hungry</b> is not an action. Use <b>be</b>: <b>Are</b> you hungry? <b>Is</b> she tired?'},
    {type:'slots', skill:'negation-and-questions', opts:['do','does','is','are'],
     text:'{do} your parents speak English?',
     why:'They / you / I + action verb: <b>Do</b> they speak?'},
    {type:'slots', skill:'negation-and-questions', opts:['do','does','is','are'],
     text:'{is} it cold today?',
     why:'<b>Cold</b> describes. Use <b>be</b>: <b>Is</b> it cold?'},
    {type:'slots', skill:'negation-and-questions', dir:'Fill in each blank.', opts:["don't","doesn't","isn't","aren't"],
     text:"My sister {doesn't} like fish. I {don't} like fish either. We {aren't} fish people!",
     why:"He / she + <b>doesn't</b>. I / you / we / they + <b>don't</b>. With <b>be</b>: isn't / aren't."},
    {type:'slots', skill:'negation-and-questions', dir:'Tap the underlined words. Fix the ones that are wrong.',
     text:'He [not likes>does not like:not likes,does not like,does not likes,no like] coffee.',
     why:'Negative: <b>does not</b> + verb with no -s. He does not <b>like</b>.'},
    {type:'slots', skill:'negation-and-questions', dir:'Tap the underlined words. Fix the ones that are wrong.',
     text:'[You are>Are you:You are,Are you,Do you,You] from Mexico?',
     why:'Questions with <b>be</b>: move <b>are</b> to the front. <b>Are you</b> from Mexico?'},
    {type:'slots', skill:'negation-and-questions', dir:'Tap the underlined words. Fix the ones that are wrong.',
     text:'[Where you live>Where do you live:Where you live,Where do you live,Where does you live,Where you do live]?',
     why:'Question word + <b>do/does</b> + person + verb: Where <b>do</b> you live?'},
    {type:'slots', skill:'negation-and-questions', dir:'Fill in each blank.', opts:['what','where','when','who','how many'],
     text:'{who} is your teacher? {how many} classes do you have? {where} is Room 210?',
     why:'<b>Who</b> = a person. <b>How many</b> = a number. <b>Where</b> = a place.'},
    {type:'order', skill:'negation-and-questions', dir:'Put the words in the correct order.',
     tiles:['start','time','class','What','does'], post:'?',
     accept:['What time does class start?'],
     why:'Question word + <b>does</b> + subject + verb: What time <b>does</b> class <b>start</b>?'}
  ]
},
{
  slug: 'adjectives-adverbs-1',
  title: 'Adjective or Adverb? 1',
  level: '101',
  directions: 'Fill in each blank. You can use a word more than once.',
  skills: ['adjectives-and-adverbs'],
  items: [
    {type:'slots', skill:'adjectives-and-adverbs', opts:['quick','quickly'],
     text:'Maya is a {quick} runner. She runs {quickly}.',
     why:'<b>Quick</b> describes a person or thing (a quick runner). <b>Quickly</b> describes an action (runs quickly).'},
    {type:'slots', skill:'adjectives-and-adverbs', opts:['loud','loudly'],
     text:"The music is too {loud}. Please don't play it so {loudly}.",
     why:'After <b>is</b>, use the adjective (is loud). After an action verb, use <b>-ly</b> (play loudly).'},
    {type:'slots', skill:'adjectives-and-adverbs', opts:['good','well'],
     text:'Leo is a {good} singer. He sings very {well}.',
     why:'<b>Good</b> describes a person. <b>Well</b> describes how you do something.'},
    {type:'slots', skill:'adjectives-and-adverbs', opts:['happy','happily'],
     text:'The children played {happily} in the park. They were very {happy}.',
     why:'Played <b>happily</b> (action). Were <b>happy</b> (after be).'},
    {type:'slots', skill:'adjectives-and-adverbs', opts:['big','bigger','biggest'],
     text:"My room is {big}, but my brother's room is {bigger}. My parents' room is the {biggest}.",
     why:'Two things: <b>bigger</b> (than). Three or more: the <b>biggest</b>.'},
    {type:'slots', skill:'adjectives-and-adverbs', opts:['good','better','best'],
     text:"This pizza is {good}. It is {better} than yesterday's pizza. It is the {best} pizza in the city!",
     why:'good \u2192 <b>better</b> \u2192 the <b>best</b>. Never "gooder."'},
    {type:'slots', skill:'adjectives-and-adverbs', dir:"Tap the underlined words. Fix the ones that are wrong.",
     text:'Tokyo is [more big>bigger:more big,bigger,biggest,more bigger] than San Francisco.',
     why:'Short words add <b>-er</b>: big\u2192bigger, tall\u2192taller. Use <b>more</b> with long words: more beautiful.'},
    {type:'slots', skill:'adjectives-and-adverbs', dir:"Tap the underlined words. Fix the ones that are wrong.",
     text:'She speaks English [perfect>perfectly:perfect,perfectly,more perfect,perfects].',
     why:'How does she speak? <b>Perfectly</b>. Action words take the <b>-ly</b> word.'},
    {type:'order', skill:'adjectives-and-adverbs', dir:'Put the words in the correct order.',
     tiles:['white','dog','small','She','a','has'], post:'.',
     accept:['She has a small white dog.'],
     why:'Size comes before color: a <b>small white</b> dog.'},
    {type:'order', skill:'adjectives-and-adverbs', dir:'Put the words in the correct order.',
     tiles:['slowly','very','drives','My','father'], post:'.',
     accept:['My father drives very slowly.'],
     why:'The <b>-ly</b> word goes after the action: drives <b>very slowly</b>.'}
  ]
},
{
  slug: 'in-on-at-place-1',
  title: 'In, On, At: Places 1',
  level: '101',
  directions: 'Fill in the blank with the correct word.',
  skills: ['prepositions'],
  items: [
    {type:'slots', skill:'prepositions', opts:['in','on','at'], text:'My keys are {on} the table.',
     why:'On top of a surface: <b>on</b> the table, <b>on</b> the floor.'},
    {type:'slots', skill:'prepositions', opts:['in','on','at'], text:'The milk is {in} the refrigerator.',
     why:'Inside something: <b>in</b> the refrigerator, <b>in</b> my bag.'},
    {type:'slots', skill:'prepositions', opts:['in','on','at'], text:'Meet me {at} the bus stop after school.',
     why:'A point or meeting place: <b>at</b> the bus stop, <b>at</b> the door.'},
    {type:'slots', skill:'prepositions', opts:['in','on','at'], text:'We live {on} Clement Street.',
     why:'Street name: <b>on</b> Clement Street.'},
    {type:'slots', skill:'prepositions', opts:['in','on','at'], text:'My cousin lives {in} Los Angeles.',
     why:'City or country: <b>in</b> Los Angeles, <b>in</b> Mexico.'},
    {type:'slots', skill:'prepositions', opts:['in','on','at'], text:'Sara lives {at} 450 Bay Street.',
     why:'Full address with a number: <b>at</b> 450 Bay Street.'},
    {type:'slots', skill:'prepositions', dir:'Fill in each blank. You can use a word more than once.', opts:['to','at','in'],
     text:'I go {to} school every day. Now I am {at/in} school. My classroom is {in} Room 210.',
     why:'Moving: go <b>to</b>. Being there: <b>at</b> school. Inside a room: <b>in</b> Room 210.'},
    {type:'slots', skill:'prepositions', dir:'Tap the underlined word. Fix it if it is wrong.',
     text:'The picture is [in>on:in,on,at] the wall.',
     why:'A picture touches the wall\u2019s surface: <b>on</b> the wall.'},
    {type:'slots', skill:'prepositions', dir:'Tap the underlined word. Fix it if it is wrong.',
     text:'I will wait for you [in>at:in,on,at] the front door.',
     why:'A point where you meet: <b>at</b> the door.'},
    {type:'slots', skill:'prepositions', dir:'Fill in each blank.', opts:['in','on','at'],
     text:'I read the news {on} my phone. I also saw the story {in} the newspaper.',
     why:'Screens: <b>on</b> my phone, <b>on</b> TV. Printed pages: <b>in</b> the newspaper, <b>in</b> a book.'}
  ]
},
{
  slug: 'present-perfect-1',
  title: 'Have / Has + Done 1',
  level: '101/103',
  directions: 'Tap the underlined word. Change it to fit the sentence.',
  skills: ['perfect-tenses'],
  items: [
    {type:'slots', skill:'perfect-tenses', text:'I have [see>seen:see,saw,seen,seed] that movie three times.',
     why:'have + <b>seen</b> (not saw). see \u2192 saw \u2192 <b>seen</b>.'},
    {type:'slots', skill:'perfect-tenses', text:'She has [go>gone:go,went,gone,goed] home.',
     why:'has + <b>gone</b>. go \u2192 went \u2192 <b>gone</b>.'},
    {type:'slots', skill:'perfect-tenses', text:'We have [eat>eaten:eat,ate,eaten,eated] lunch already.',
     why:'have + <b>eaten</b>. eat \u2192 ate \u2192 <b>eaten</b>.'},
    {type:'slots', skill:'perfect-tenses', text:'They [has>have:has,have,had,having] lived here for two years.',
     why:'They / I / we / you + <b>have</b>. He / she / it + <b>has</b>.'},
    {type:'slots', skill:'perfect-tenses', dir:'Fill in each blank.', opts:['for','since'],
     text:'I have lived in San Francisco {for} three years. My sister has lived here {since} 2024.',
     why:'<b>For</b> + an amount of time (three years). <b>Since</b> + a starting point (2024).'},
    {type:'slots', skill:'perfect-tenses', dir:'Fill in each blank.', opts:['for','since'],
     text:'We have been friends {since} sixth grade. I have known her {for} a long time.',
     why:'<b>Since</b> sixth grade (start). <b>For</b> a long time (amount).'},
    {type:'slots', skill:'perfect-tenses', dir:'Fill in each blank.', opts:['ever','never','already','yet'],
     text:'Have you {ever} been to New York? No, I have {never} been there.',
     why:'Questions about your whole life: <b>ever</b>. Not one time: <b>never</b>.'},
    {type:'slots', skill:'perfect-tenses', dir:'Choose the best answer.', opts:['lived','has lived','lives','is living'],
     text:'My grandma {has lived} in Guatemala since 1970.',
     why:'Started in the past and still true now + <b>since</b>: <b>has lived</b>.'},
    {type:'slots', skill:'perfect-tenses', dir:'Choose the best answer.', opts:['went','has gone','goes','have gone'],
     text:'Last summer, we {went} to the beach.',
     why:'A finished time (<b>last summer</b>) uses the simple past: <b>went</b>.'},
    {type:'order', skill:'perfect-tenses', dir:'Put the words in the correct order.',
     tiles:['homework','finished','I','my','have'], post:'.',
     accept:['I have finished my homework.'],
     why:'Person + <b>have</b> + done-word + the rest.'}
  ]
},
{
  slug: 'progressive-1',
  title: 'Happening Now (-ing) 1',
  level: '101',
  directions: 'Tap the underlined word. Change it to fit the sentence.',
  skills: ['progressive-tenses'],
  items: [
    {type:'slots', skill:'progressive-tenses', text:'Shh! The baby [sleep>is sleeping:sleep,sleeps,is sleeping,sleeping] now.',
     why:'Happening now: <b>is</b> + verb<b>-ing</b>.'},
    {type:'slots', skill:'progressive-tenses', text:'Look! It [rain>is raining:rain,rains,is raining,raining].',
     why:'<b>Look!</b> means now: <b>is raining</b>.'},
    {type:'slots', skill:'progressive-tenses', text:'They [are play>are playing:are play,are playing,is playing,playing] soccer right now.',
     why:'<b>are</b> + <b>-ing</b>. Both parts are needed.'},
    {type:'slots', skill:'progressive-tenses', dir:'Fill in each blank.', opts:['am','is','are'],
     text:'I {am} reading. My mom {is} cooking. My brothers {are} watching TV.',
     why:'I <b>am</b>. He / she <b>is</b>. They <b>are</b>.'},
    {type:'slots', skill:'progressive-tenses', dir:'Fill in each blank.', opts:['was','were'],
     text:'I {was} sleeping when you called. My parents {were} working.',
     why:'In the past: I / he / she <b>was</b>. We / you / they <b>were</b>.'},
    {type:'slots', skill:'progressive-tenses', dir:'Choose the best answer.', opts:['walk','walked','was walking','am walking'],
     text:'I {was walking} home when I saw my friend.',
     why:'A longer action (<b>was walking</b>) and a short action in the middle (<b>saw</b>).'},
    {type:'slots', skill:'progressive-tenses', dir:'Fill in each blank.', opts:['studies','is studying','studied','study'],
     text:'Every day, Kim {studies} English. Right now, she {is studying} math.',
     why:'<b>Every day</b> = habit (studies). <b>Right now</b> = is studying.'},
    {type:'slots', skill:'progressive-tenses', dir:'Choose the best answer.', opts:['know','am knowing'],
     text:'I {know} the answer!',
     why:'Some verbs are not actions: <b>know, like, want, need</b>. They do not use -ing.'},
    {type:'slots', skill:'progressive-tenses', dir:'Choose the best answer.', opts:['want','am wanting'],
     text:'I {want} a glass of water, please.',
     why:'<b>Want</b> is a feeling, not an action. Say <b>I want</b>.'},
    {type:'order', skill:'progressive-tenses', dir:'Put the words in the correct order.',
     tiles:['TV','is','sister','watching','My'], post:'.',
     accept:['My sister is watching TV.'],
     why:'Person + <b>is</b> + verb<b>-ing</b> + the rest.'}
  ]
},
{
  slug: 'modals-contractions-1',
  title: "Can, Could, Should + Don't, Won't 1",
  level: '101',
  directions: 'Choose the best word for each blank.',
  skills: ['modals-and-contractions'],
  items: [
    {type:'slots', skill:'modals-and-contractions', dir:"Change the underlined part into one word with an apostrophe ( ' ).",
     text:"I [can not>can't:can not,can't,cann't,ca'nt] find my phone.",
     why:"can not \u2192 <b>can't</b>."},
    {type:'slots', skill:'modals-and-contractions', dir:"Change the underlined part into one word with an apostrophe ( ' ).",
     text:"She [does not>doesn't:does not,doesn't,does'nt,dosen't] like rain.",
     why:"The apostrophe takes the place of the <b>o</b> in not: does not \u2192 <b>doesn't</b>."},
    {type:'slots', skill:'modals-and-contractions', dir:"Change the underlined part into one word with an apostrophe ( ' ).",
     text:"[It is>It's:It is,It's,Its,Its'] cold today.",
     why:"it is \u2192 <b>it's</b>. (<b>its</b> with no apostrophe means \u201cbelongs to it.\u201d)"},
    {type:'slots', skill:'modals-and-contractions', dir:"Change the underlined part into one word with an apostrophe ( ' ).",
     text:"We [will not>won't:will not,won't,willn't,wo'nt] be late.",
     why:"will not \u2192 <b>won't</b>. This one is special!"},
    {type:'slots', skill:'modals-and-contractions', opts:['can','could','should','must'],
     text:'When I was little, I {could} climb trees.',
     why:'Ability in the past: <b>could</b>. Ability now: <b>can</b>.'},
    {type:'slots', skill:'modals-and-contractions', opts:['should','can','would','did'],
     text:'That cough sounds bad. You {should} see a doctor.',
     why:'Advice: <b>should</b>. You <b>should</b> rest. You <b>should</b> drink water.'},
    {type:'slots', skill:'modals-and-contractions', opts:['would','will','can','should'],
     text:'{would} you like some tea?',
     why:'A polite offer: <b>Would you like</b>...?'},
    {type:'slots', skill:'modals-and-contractions', opts:['can','can to','cans','canning'],
     text:'My brother {can} speak three languages.',
     why:'<b>Can</b> never changes: I can, he can. No <b>to</b>, no <b>-s</b>.'},
    {type:'slots', skill:'modals-and-contractions', dir:'Tap the underlined word. Fix it if it is wrong.',
     text:'She can [speaks>speak:speaks,speak,speaking,to speak] Chinese.',
     why:'After <b>can, could, should, will</b>: the plain verb. She can <b>speak</b>.'},
    {type:'slots', skill:'modals-and-contractions', opts:["couldn't","can't","won't","shouldn't"],
     text:"I {couldn't} go to school yesterday because I was sick.",
     why:"<b>Yesterday</b> = past. Not able in the past: <b>couldn't</b>."}
  ]
},
{
  slug: 'gerunds-infinitives-1',
  title: 'To Go or Going? 1',
  level: '103',
  directions: 'Choose the best words for each blank.',
  skills: ['gerunds-infinitives'],
  items: [
    {type:'slots', skill:'gerunds-infinitives', opts:['to eat','eating'], text:'I want {to eat} pizza tonight.',
     why:'<b>want</b> + <b>to</b> + verb: want to eat, want to go.'},
    {type:'slots', skill:'gerunds-infinitives', opts:['to eat','eating'], text:'I enjoy {eating} with my family.',
     why:'<b>enjoy</b> + verb<b>-ing</b>: enjoy eating, enjoy playing.'},
    {type:'slots', skill:'gerunds-infinitives', opts:['to go','going'], text:'We decided {to go} to the park.',
     why:'<b>decide</b> + <b>to</b>: decided to go.'},
    {type:'slots', skill:'gerunds-infinitives', opts:['to go','going'], text:'Do you feel like {going} out tonight?',
     why:'<b>feel like</b> + <b>-ing</b>: feel like going.'},
    {type:'slots', skill:'gerunds-infinitives', opts:['to swim','swimming'], text:'{swimming/to swim} is good exercise.',
     why:'As the subject of a sentence, <b>-ing</b> is most common: <b>Swimming</b> is fun.'},
    {type:'slots', skill:'gerunds-infinitives', opts:['to finish','finishing'], text:'I need {to finish} my essay today.',
     why:'<b>need</b> + <b>to</b>: need to finish.'},
    {type:'slots', skill:'gerunds-infinitives', opts:['to call','calling'], text:'Please remember {to call} your grandmother.',
     why:'<b>remember to</b> = don\u2019t forget to do it.'},
    {type:'slots', skill:'gerunds-infinitives', dir:'Fill in each blank.', opts:['bored','boring'],
     text:'This book is {boring}. I am {bored}.',
     why:'<b>-ing</b> = the thing that causes the feeling. <b>-ed</b> = how the person feels.'},
    {type:'slots', skill:'gerunds-infinitives', dir:'Fill in each blank.', opts:['excited','exciting'],
     text:'The game was {exciting}! Everyone was {excited}.',
     why:'The game was <b>exciting</b>. The people were <b>excited</b>.'},
    {type:'slots', skill:'gerunds-infinitives', dir:'Tap the underlined word. Fix it if it is wrong.',
     text:'She is good at [draw>drawing:draw,drawing,to draw,draws].',
     why:'After <b>at, in, of, about</b>: use <b>-ing</b>. Good at <b>drawing</b>.'}
  ]
},
{
  slug: 'joining-sentences-2',
  title: 'Joining Sentences 2: Because, Although, If',
  level: '103',
  directions: 'Combine the sentences into one sentence. Choose the best joining word.',
  skills: ['complex-sentences'],
  items: [
    {type:'write', skill:'complex-sentences', words:['because','although','if','when'],
     prompt:'I was late. I missed the bus.',
     accept:['I was late because I missed the bus.','Because I missed the bus, I was late.'],
     why:'<b>Because</b> gives the reason. If <b>because</b> comes first, put a comma after that part.'},
    {type:'write', skill:'complex-sentences', words:['because','although','if','when'],
     prompt:'It was cold. We went swimming.',
     accept:['Although it was cold, we went swimming.','We went swimming although it was cold.'],
     why:'<b>Although</b> shows a surprise: cold, but we swam anyway.'},
    {type:'write', skill:'complex-sentences', words:['because','although','if','when'],
     prompt:'You study. You will pass the test.',
     accept:['If you study, you will pass the test.','You will pass the test if you study.'],
     why:'<b>If</b> shows a condition. Comma only when <b>if</b> comes first.'},
    {type:'write', skill:'complex-sentences', words:['because','although','if','when'],
     prompt:'Maria is happy. She got a new job.',
     accept:['Maria is happy because she got a new job.','Because she got a new job, Maria is happy.'],
     why:'The new job is the reason: <b>because</b>.'},
    {type:'write', skill:'complex-sentences', words:['because','although','if','when'],
     prompt:'My brother is young. He is very tall.',
     accept:['Although my brother is young, he is very tall.','My brother is very tall although he is young.'],
     why:'Young but tall is a surprise: <b>although</b>.'},
    {type:'write', skill:'complex-sentences', words:['because','although','if','when'],
     prompt:'I get home. I eat a snack.',
     accept:['When I get home, I eat a snack.','I eat a snack when I get home.'],
     why:'<b>When</b> tells the time.'},
    {type:'order', skill:'complex-sentences', dir:'Put the words in order to make one sentence.',
     tiles:['we','raining,','Because','stayed','was','home','it'], post:'.',
     accept:['Because it was raining, we stayed home.'],
     why:'<b>Because</b> part first, then a comma, then the main sentence.'},
    {type:'write', skill:'complex-sentences', words:['unless'],
     prompt:'You cannot go outside. You finish your homework.',
     accept:['You cannot go outside unless you finish your homework.','Unless you finish your homework, you cannot go outside.'],
     why:'<b>Unless</b> = if not. No homework, no outside.'}
  ]
},
{
  slug: 'however-therefore-1',
  title: 'However, Therefore, In Addition 1',
  level: '103',
  directions: 'Use one of the joining words to connect the sentences. You can write one sentence or two.',
  skills: ['conjunctive-adverbs'],
  items: [
    {type:'write', skill:'conjunctive-adverbs', words:['however','therefore','in addition'],
     prompt:'It was raining. We played soccer.',
     accept:['It was raining; however, we played soccer.','It was raining. However, we played soccer.'],
     why:'Something unexpected: <b>however</b>. Write <b>; however,</b> or <b>. However,</b>'},
    {type:'write', skill:'conjunctive-adverbs', words:['however','therefore','in addition'],
     prompt:'I studied very hard. I got an A.',
     accept:['I studied very hard; therefore, I got an A.','I studied very hard. Therefore, I got an A.'],
     why:'A result: <b>therefore</b> (= so).'},
    {type:'write', skill:'conjunctive-adverbs', words:['however','therefore','in addition'],
     prompt:'The movie was too long. It was boring.',
     accept:['The movie was too long; in addition, it was boring.','The movie was too long. In addition, it was boring.'],
     why:'One more idea of the same kind: <b>in addition</b> (= also).'},
    {type:'write', skill:'conjunctive-adverbs', words:['however','therefore','in addition'],
     prompt:'The store was closed. We went home.',
     accept:['The store was closed; therefore, we went home.','The store was closed. Therefore, we went home.'],
     why:'Closed store \u2192 went home. A result: <b>therefore</b>.'},
    {type:'write', skill:'conjunctive-adverbs', words:['however','therefore','in addition'],
     prompt:'Lucas is shy. He loves to sing on stage.',
     accept:['Lucas is shy; however, he loves to sing on stage.','Lucas is shy. However, he loves to sing on stage.'],
     why:'Shy but sings on stage is a surprise: <b>however</b>.'},
    {type:'write', skill:'conjunctive-adverbs', words:['however','therefore','in addition'],
     prompt:'Exercise is good for your body. It helps you sleep.',
     accept:['Exercise is good for your body; in addition, it helps you sleep.','Exercise is good for your body. In addition, it helps you sleep.'],
     why:'Two good things about exercise: <b>in addition</b>.'},
    {type:'slots', skill:'conjunctive-adverbs', dir:'Choose the best word for the blank.', opts:['however','therefore','in addition'],
     text:'Tomas missed the bus; {therefore}, he walked to school.',
     why:'Missed bus \u2192 walked. A result: <b>therefore</b>.'},
    {type:'slots', skill:'conjunctive-adverbs', dir:'Choose the best word for the blank.', opts:['however','therefore','in addition'],
     text:"I like tea; {however}, I don't like coffee.",
     why:'Like tea, but not coffee. A contrast: <b>however</b>.'}
  ]
}
];
