/* data.js — Mary Walks Home (VETS Story 02). One source of truth for every practice page. */
window.SD = window.SD || {};
SD.STORY = 'story-02';
SD.NN = '02';
SD.TITLE = "Mary Walks Home";
SD.SUB = "A woman walks eight miles every day.";
SD.STORY_URL = '../vets_story_02.html';
SD.ART = {};
SD.VOCAB = [{"w": "bank", "pic": "🏦", "gloss": "a place for money", "s": "Mary works at a ___."}, {"w": "works", "pic": "👩‍💼", "gloss": "has a job", "s": "Mary ___ at a bank."}, {"w": "morning", "pic": "🌅", "gloss": "the early part of the day", "s": "She begins at eight in the ___."}, {"w": "afternoon", "pic": "🌤️", "gloss": "after 12:00, before evening", "s": "She stops at five in the ___."}, {"w": "closes", "pic": "🔒", "gloss": "stops being open", "s": "At five o’clock the bank ___."}, {"w": "drive", "pic": "🚗", "gloss": "go by car", "s": "Some people ___ home."}, {"w": "train", "pic": "🚆", "gloss": "a long vehicle on rails", "s": "Some people take the ___."}, {"w": "bus", "pic": "🚌", "gloss": "a big vehicle for many people", "s": "Some people take the ___."}, {"w": "walks", "pic": "🚶‍♀️", "gloss": "goes on foot", "s": "Mary ___ home."}, {"w": "miles", "pic": "🛣️", "gloss": "a way to measure distance", "s": "Mary lives eight ___ from the bank."}, {"w": "dinner", "pic": "🍽️", "gloss": "the evening meal", "s": "She eats ___."}, {"w": "tired", "pic": "😴", "gloss": "wanting to rest", "s": "Mary is ___."}];
SD.SENTS = ["Mary works at a bank.", "She begins working at eight o’clock in the morning.", "She stops working at five o’clock in the afternoon.", "At five o’clock, the bank closes.", "Everybody goes home.", "Some people drive home.", "Some people take the train.", "Some people take the bus.", "Mary walks home.", "She likes to walk.", "Mary lives eight miles from the bank.", "She walks for three hours.", "She eats dinner.", "Then she goes to bed.", "Mary is 82 years old."];
SD.SOUNDS = [{"name": "a as in bank", "key": "bank", "words": ["bank", "at", "afternoon", "than", "and"]}, {"name": "o as in home", "key": "home", "words": ["home", "closes", "goes", "so", "old"]}, {"name": "ai / ay as in train", "key": "train", "words": ["train", "Mary", "day", "eight", "takes"]}];
SD.SPELL = [{"w": "bank", "hide": [1, 2]}, {"w": "morning", "hide": [1, 4]}, {"w": "afternoon", "hide": [1, 5]}, {"w": "closes", "hide": [2, 4]}, {"w": "drive", "hide": [2, 4]}, {"w": "train", "hide": [2, 3]}, {"w": "walks", "hide": [1, 3]}, {"w": "miles", "hide": [1, 3]}, {"w": "dinner", "hide": [1, 4]}, {"w": "tired", "hide": [1, 3]}];
SD.WRITE = ["Mary works at a bank.", "At five o’clock the bank closes.", "Some people take the bus.", "Mary walks home.", "She walks for three hours.", "Then she goes to bed.", "Mary is 82 years old."];
SD.DICT = {"word": [{"say": "bank", "opts": ["bank", "back", "bake"]}, {"say": "train", "opts": ["train", "tray", "rain"]}, {"say": "bus", "opts": ["bus", "boss", "us"]}, {"say": "walks", "opts": ["walks", "works", "wax"]}, {"say": "eight", "opts": ["eight", "ate", "late"]}, {"say": "dinner", "opts": ["dinner", "winner", "thinner"]}, {"say": "home", "opts": ["home", "come", "hum"]}, {"say": "tired", "opts": ["tired", "tied", "tire"]}], "phrase": [{"say": "at eight o’clock", "extra": ["nine"]}, {"say": "in the morning", "extra": ["evening"]}, {"say": "eight miles", "extra": ["hours"]}, {"say": "for three hours", "extra": ["four"]}, {"say": "goes to bed", "extra": ["work"]}, {"say": "take the bus", "extra": ["train"]}], "sentence": [{"say": "Mary works at a bank.", "extra": ["walks"]}, {"say": "Some people take the train.", "extra": ["bus"]}, {"say": "Mary walks home.", "extra": ["drives"]}, {"say": "She walks for three hours.", "extra": ["eight"]}, {"say": "Then she goes to bed.", "extra": ["he"]}, {"say": "Mary is 82 years old.", "extra": ["28"]}]};
SD.GRAMMAR = [{"id": "time", "title": "At eight o’clock, in the morning", "skill": "PREP.TIME", "items": [{"p": "She begins ___ eight o’clock.", "o": ["at", "in", "on"], "a": "at"}, {"p": "She works ___ the morning.", "o": ["in", "at", "on"], "a": "in"}, {"p": "The bank closes ___ five.", "o": ["at", "in", "on"], "a": "at"}, {"p": "She walks ___ three hours.", "o": ["for", "at", "in"], "a": "for"}, {"p": "She goes to bed ___ night.", "o": ["at", "in", "on"], "a": "at"}]}, {"id": "sv", "title": "She walks, they walk", "skill": "SV.3SG", "items": [{"p": "Mary ___ at a bank.", "o": ["work", "works"], "a": "works"}, {"p": "Some people ___ the bus.", "o": ["take", "takes"], "a": "take"}, {"p": "She ___ eight miles from the bank.", "o": ["live", "lives"], "a": "lives"}, {"p": "Everybody ___ home.", "o": ["go", "goes"], "a": "goes"}, {"p": "They ___ home.", "o": ["drive", "drives"], "a": "drive"}]}, {"id": "neg", "title": "Does not", "skill": "NEG.DOES", "items": [{"p": "Mary ___ drive.", "o": ["does not", "do not", "not"], "a": "does not"}, {"p": "She ___ take the train.", "o": ["doesn’t", "don’t", "isn’t"], "a": "doesn’t"}, {"p": "They ___ walk home.", "o": ["don’t", "doesn’t", "aren’t"], "a": "don’t"}]}, {"id": "like", "title": "Likes to + verb", "skill": "LIKE.TO", "items": [{"p": "She likes ___ walk.", "o": ["to", "for", "at"], "a": "to"}, {"p": "Mary likes to ___.", "o": ["walk", "walks", "walking"], "a": "walk"}, {"p": "I like ___ take the bus.", "o": ["to", "the", "a"], "a": "to"}]}];
SD.ME = {"prompt": "Mary walks home. And you? How do you go home? Finish the sentence, then say it.", "before": "I", "after": "home.", "options": ["walk", "take the bus", "take the train", "drive", "ride a bike"]};
